In [4]:
#import libraries

import pandas as pd

In [5]:
#Read election data
county_elections_df = pd.read_csv('Resources/countypres_2000-2020.csv')
county_elections_df.head()

,year,state,state_po,county_name,county_fips,office,candidate,party,candidatevotes,totalvotes,version,mode
0,2000,ALABAMA,AL,AUTAUGA,1001.0,US PRESIDENT,AL GORE,DEMOCRAT,4942,17208,20220315,TOTAL
1,2000,ALABAMA,AL,AUTAUGA,1001.0,US PRESIDENT,GEORGE W. BUSH,REPUBLICAN,11993,17208,20220315,TOTAL
2,2000,ALABAMA,AL,AUTAUGA,1001.0,US PRESIDENT,RALPH NADER,GREEN,160,17208,20220315,TOTAL
3,2000,ALABAMA,AL,AUTAUGA,1001.0,US PRESIDENT,OTHER,OTHER,113,17208,20220315,TOTAL
4,2000,ALABAMA,AL,BALDWIN,1003.0,US PRESIDENT,AL GORE,DEMOCRAT,13997,56480,20220315,TOTAL

In [55]:
#Looking how does the dataset is divided in a county

county_elections_df[county_elections_df['county_fips'] == 4001]

,year,state,state_po,county_name,county_fips,office,candidate,party,candidatevotes,totalvotes,version,mode
268,2000,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,AL GORE,DEMOCRAT,13025,19456,20220315,TOTAL
269,2000,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,GEORGE W. BUSH,REPUBLICAN,5947,19456,20220315,TOTAL
270,2000,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,RALPH NADER,GREEN,245,19456,20220315,TOTAL
271,2000,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,OTHER,OTHER,239,19456,20220315,TOTAL
12665,2004,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,JOHN KERRY,DEMOCRAT,15658,24198,20220315,TOTAL
12666,2004,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,GEORGE W. BUSH,REPUBLICAN,8384,24198,20220315,TOTAL
12667,2004,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,OTHER,OTHER,156,24198,20220315,TOTAL
22016,2008,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,BARACK OBAMA,DEMOCRAT,15390,24262,20220315,TOTAL
22017,2008,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,JOHN MCCAIN,REPUBLICAN,8551,24262,20220315,TOTAL
22018,2008,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,OTHER,OTHER,321,24262,20220315,TOTAL
31367,2012,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,BARACK OBAMA,DEMOCRAT,17147,25848,20220315,TOTAL
31368,2012,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,MITT ROMNEY,REPUBLICAN,8250,25848,20220315,TOTAL
31369,2012,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,OTHER,OTHER,451,25848,20220315,TOTAL
40718,2016,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,HILLARY CLINTON,DEMOCRAT,17083,27661,20220315,TOTAL
40719,2016,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,DONALD TRUMP,REPUBLICAN,8240,27661,20220315,TOTAL
40720,2016,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,OTHER,OTHER,2338,27661,20220315,TOTAL
50930,2020,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,JOSEPH R BIDEN JR,DEMOCRAT,16460,35172,20220315,EARLY VOTE
50931,2020,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,JOSEPH R BIDEN JR,DEMOCRAT,6539,35172,20220315,ELECTION DAY
50932,2020,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,JOSEPH R BIDEN JR,DEMOCRAT,294,35172,20220315,PROVISIONAL
50933,2020,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,OTHER,GREEN,0,35172,20220315,EARLY VOTE
50934,2020,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,OTHER,GREEN,0,35172,20220315,ELECTION DAY
50935,2020,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,OTHER,GREEN,0,35172,20220315,PROVISIONAL
50936,2020,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,JO JORGENSEN,LIBERTARIAN,311,35172,20220315,EARLY VOTE
50937,2020,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,JO JORGENSEN,LIBERTARIAN,122,35172,20220315,ELECTION DAY
50938,2020,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,JO JORGENSEN,LIBERTARIAN,4,35172,20220315,PROVISIONAL
50939,2020,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,OTHER,OTHER,0,35172,20220315,EARLY VOTE
50940,2020,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,OTHER,OTHER,0,35172,20220315,ELECTION DAY
50941,2020,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,OTHER,OTHER,0,35172,20220315,PROVISIONAL
50942,2020,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,7262,35172,20220315,EARLY VOTE
50943,2020,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,4053,35172,20220315,ELECTION DAY
50944,2020,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,127,35172,20220315,PROVISIONAL

In [8]:
#Importing population dataset and transforming it into a DataFrame
population_county_df = pd.read_csv('Resources/co-est2019-alldata.csv', encoding_errors='ignore')
population_county_df

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2019,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015,RNETMIG2016,RNETMIG2017,RNETMIG2018,RNETMIG2019
0,40,3,6,1,0,Alabama,Alabama,4779736,4780125,4785437,...,1.917501,0.578434,1.186314,1.522549,0.563489,0.626357,0.745172,1.090366,1.773786,2.483744
1,50,3,6,1,1,Alabama,Autauga County,54571,54597,54773,...,4.847310,6.018182,-6.226119,-3.902226,1.970443,-1.712875,4.777171,0.849656,0.540916,4.560062
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183112,...,24.017829,16.641870,17.488579,22.751474,20.184334,17.725964,21.279291,22.398256,24.727215,24.380567
3,50,3,6,1,5,Alabama,Barbour County,27457,27455,27327,...,-5.690302,0.292676,-6.897817,-8.132185,-5.140431,-15.724575,-18.238016,-24.998528,-8.754922,-5.165664
4,50,3,6,1,7,Alabama,Bibb County,22915,22915,22870,...,1.385134,-4.998356,-3.787545,-5.797999,1.331144,1.329817,-0.708717,-3.234669,-6.857092,1.831952
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,50,4,8,56,37,Wyoming,Sweetwater County,43806,43806,43574,...,-17.605427,0.502513,15.035735,-4.614071,-13.140225,-13.762031,-18.484164,-23.515727,-18.743773,-17.065527
3189,50,4,8,56,39,Wyoming,Teton County,21294,21298,21296,...,-1.583464,-2.575509,1.905293,23.259519,12.508872,4.670450,1.253214,-0.171608,-12.432212,1.797445
3190,50,4,8,56,41,Wyoming,Uinta County,21118,21121,21089,...,-9.181105,-18.196975,-4.487730,-10.870861,-15.033634,-10.484550,-11.485101,-18.923455,-13.554993,-9.181105
3191,50,4,8,56,43,Wyoming,Washakie County,8533,8528,8530,...,-7.652085,-12.839390,-3.084589,-1.307811,-18.938032,0.000000,-15.204038,-15.950541,-17.246806,-8.289759
3192,50,4,8,56,45,Wyoming,Weston County,7208,7208,7198,...,0.000000,-9.065551,-10.549265,6.191515,0.420345,9.201171,0.693097,-36.227798,-6.910452,2.599090

In [132]:
# Importing Debt dataset and transforming it into a DataFrame
Debt_data_df = pd.read_csv('Resources/debt.csv')

Debt_data_df

,NAME,GEOID,state_name,"Auto/Retail Debt Delinquency Rate, All","Auto/Retail Debt Delinquency Rate, Communities of Color","Auto/Retail Debt Delinquency Rate, Majority White Communities","Share of Subprime Consumers with Auto/Retail Delinquencies, All","Share of Near-Prime Consumers with Auto/Retail Delinquencies, All","Share of Prime Consumers with Auto/Retail Delinquencies, All","Share with Open Auto Debt, All","Share with Open Auto Debt, Communities of Color","Share with Open Auto Debt, Majority White Communities","Share with Open Auto/Retail Debt, All","Share with Open Auto/Retail Debt, Communities of Color","Share with Open Auto/Retail Debt, Majority White Communities","% population in rural areas, 2010 (Census)",poc_pct,"Average household income, 2019 (ACS)","Average non-white household income, 2019 (ACS)","Average white, non-Hispanic household income, 2019 (ACS)"
0,"Autauga County, Alabama",1001,Alabama,0.0634218,n/a*,0.0650155,0.2628205,0.0130719,0,0.2623955,n/a*,0.2649472,0.3727019,n/a*,0.3733881,0.420022,0.253973,75326,50809,82971
1,"Baldwin County, Alabama",1003,Alabama,0.0428429,n/a**,0.0427753,0.2402464,0.0205339,0.0004912,0.33154,n/a**,0.3327853,0.3993275,n/a**,0.4010139,0.422791,0.169276,81449,47333,86522
2,"Barbour County, Alabama",1005,Alabama,0.0868167,n/a*,n/a*,0.297619,0.015873,0,0.2787958,0.2435897,0.3454545,0.3979058,0.2948718,0.4181818,0.677896,0.541895,47068,31673,63382
3,"Bibb County, Alabama",1007,Alabama,0.1048689,n/a**,0.0917031,0.3246753,n/a*,0,0.3047619,n/a**,0.3118081,0.4111111,n/a**,0.4095941,0.683526,0.254746,60182,40249,65273
4,"Blount County, Alabama",1009,Alabama,0.0407876,n/a*,0.0407876,0.1746988,0,0,0.2988116,n/a*,0.2989807,0.3978495,n/a*,0.3980747,0.899515,0.131066,65639,49595,67146
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3132,"Sweetwater County, Wyoming",56037,Wyoming,0.042735,n/a**,0.0434783,0.25,0.0163934,0,0.4200164,n/a**,0.4255499,0.4757998,n/a**,0.4822335,0.109163,0.204430,85346,64674,89540
3133,"Teton County, Wyoming",56039,Wyoming,0.0040984,n/a**,0.005814,n/a*,n/a*,0,0.2642424,n/a**,0.2479609,0.2957576,n/a**,0.2805873,0.464309,0.186641,132531,71564,141299
3134,"Uinta County, Wyoming",56041,Wyoming,0.0283688,n/a**,0.0290909,n/a*,n/a*,0,0.4119658,n/a**,0.4179894,0.4820513,n/a**,0.4850088,0.430959,0.124811,74938,72010,75273
3135,"Washakie County, Wyoming",56043,Wyoming,0.0123457,n/a**,0.0123457,n/a*,n/a*,0,0.2627451,n/a**,0.2627451,0.3176471,n/a**,0.3176471,0.359545,0.181014,65496,56047,67192
3136,"Weston County, Wyoming",56045,Wyoming,0.019802,n/a**,0.019802,n/a*,n/a*,0,0.387931,n/a**,0.3896104,0.4353448,n/a**,0.4372294,0.545366,0.036317,68877,37509,69485

## Exploring the data

In [11]:
# checking length
len(county_elections_df)

72617

In [12]:
#values in each state
county_elections_df.state.value_counts()

TEXAS                   5334
GEORGIA                 4452
VIRGINIA                3736
NORTH CAROLINA          3600
ARKANSAS                2700
IOWA                    2574
MISSOURI                2436
KENTUCKY                2400
OKLAHOMA                2156
ILLINOIS                2142
SOUTH CAROLINA          2116
KANSAS                  1995
INDIANA                 1932
MINNESOTA               1827
TENNESSEE               1805
NEBRASKA                1767
OHIO                    1760
MICHIGAN                1743
MISSISSIPPI             1722
WISCONSIN               1512
FLORIDA                 1407
COLORADO                1340
NEW YORK                1302
LOUISIANA               1280
ALABAMA                 1273
PENNSYLVANIA            1273
SOUTH DAKOTA            1254
CALIFORNIA              1218
WEST VIRGINIA           1100
MONTANA                 1064
NORTH DAKOTA            1060
UTAH                    1039
MARYLAND                 984
IDAHO                    880
ALASKA                   861
WASHINGTON               819
OREGON                   756
NEW MEXICO               693
ARIZONA                  465
WYOMING                  460
NEW JERSEY               441
MAINE                    352
NEVADA                   340
MASSACHUSETTS            294
VERMONT                  294
NEW HAMPSHIRE            190
CONNECTICUT              184
RHODE ISLAND             120
HAWAII                    84
DELAWARE                  60
DISTRICT OF COLUMBIA      21
Name: state, dtype: int64

In [13]:
#Values in each county
county_elections_df.county_name.value_counts()

WASHINGTON           727
FRANKLIN             576
JEFFERSON            563
JACKSON              541
LINCOLN              532
                    ...
HAMPTON CITY          12
HARRISONBURG CITY     12
WINCHESTER CITY       12
NORTON CITY            8
OGLALA LAKOTA          6
Name: county_name, Length: 1892, dtype: int64

In [57]:
#Total counties in the dataset
len(county_elections_df.county_name.unique())

1892

In [15]:
#Total states
len(county_elections_df.state.unique())

51

In [17]:
#Checking the columns that are in the DataFrame
print(population_county_df.columns)

Index(['SUMLEV', 'REGION', 'DIVISION', 'STATE', 'COUNTY', 'STNAME', 'CTYNAME',
       'CENSUS2010POP', 'ESTIMATESBASE2010', 'POPESTIMATE2010',
       ...
       'RDOMESTICMIG2019', 'RNETMIG2011', 'RNETMIG2012', 'RNETMIG2013',
       'RNETMIG2014', 'RNETMIG2015', 'RNETMIG2016', 'RNETMIG2017',
       'RNETMIG2018', 'RNETMIG2019'],
      dtype='object', length=164)

## Cleaning data

In [18]:
#Drop Columns that are not usable in the data sets

population_df = population_county_df[['CTYNAME','POPESTIMATE2019','INTERNATIONALMIG2019']]
population_df

                CTYNAME  POPESTIMATE2019  INTERNATIONALMIG2019
0               Alabama          4903185                  2772
1        Autauga County            55869                   -16
2        Baldwin County           223234                    80
3        Barbour County            24686                    13
4           Bibb County            22394                    10
...                 ...              ...                   ...
3188  Sweetwater County            42343                    23
3189       Teton County            23464                    79
3190       Uinta County            20226                     0
3191    Washakie County             7805                    -5
3192      Weston County             6927                    18

[3193 rows x 3 columns]

In [19]:
#Drop columns that are not useful in debt DataFrame
debt_df = Debt_data_df[['NAME','Share with Open Auto Debt, All', 'Share with Open Auto Debt, Communities of Color', 'Share with Open Auto Debt, Majority White Communities', 'Average household income, 2019 (ACS)', 'Average non-white household income, 2019 (ACS)', 'Average white, non-Hispanic household income, 2019 (ACS)']]
debt_df

,NAME,"Share with Open Auto/Retail Debt, All","Share with Open Auto Debt, Communities of Color","Share with Open Auto Debt, Majority White Communities","Average household income, 2019 (ACS)","Average non-white household income, 2019 (ACS)","Average white, non-Hispanic household income, 2019 (ACS)"
0,"Autauga County, Alabama",0.3727019,n/a*,0.2649472,75326,50809,82971
1,"Baldwin County, Alabama",0.3993275,n/a**,0.3327853,81449,47333,86522
2,"Barbour County, Alabama",0.3979058,0.2435897,0.3454545,47068,31673,63382
3,"Bibb County, Alabama",0.4111111,n/a**,0.3118081,60182,40249,65273
4,"Blount County, Alabama",0.3978495,n/a*,0.2989807,65639,49595,67146
...,...,...,...,...,...,...,...
3132,"Sweetwater County, Wyoming",0.4757998,n/a**,0.4255499,85346,64674,89540
3133,"Teton County, Wyoming",0.2957576,n/a**,0.2479609,132531,71564,141299
3134,"Uinta County, Wyoming",0.4820513,n/a**,0.4179894,74938,72010,75273
3135,"Washakie County, Wyoming",0.3176471,n/a**,0.2627451,65496,56047,67192
3136,"Weston County, Wyoming",0.4353448,n/a**,0.3896104,68877,37509,69485

In [64]:
#Dropping the columns that are not useful and cutting the data to the year 2020


elections_df = county_elections_df[county_elections_df['year'] == 2020]
elections_df = elections_df.drop(columns = ['office', 'candidate', 'totalvotes', 'version','year','mode', 'state', 'state_po', 'county_fips'])


elections_df

      county_name        party  candidatevotes
50524     AUTAUGA     DEMOCRAT            7503
50525     AUTAUGA        OTHER             429
50526     AUTAUGA   REPUBLICAN           19838
50527     BALDWIN     DEMOCRAT           24578
50528     BALDWIN        OTHER            1557
...           ...          ...             ...
72612    WASHAKIE   REPUBLICAN            3245
72613      WESTON     DEMOCRAT             360
72614      WESTON  LIBERTARIAN              46
72615      WESTON        OTHER              47
72616      WESTON   REPUBLICAN            3107

[22093 rows x 3 columns]

In [65]:
# Drop duplicates of the columns
elections_df1 = elections_df.drop_duplicates()

In [66]:
#Use a Pivot table to transform our dataframe and get the total votes for each party
total_elections_df=elections_df1.pivot_table(index='county_name', columns = 'party', values = 'candidatevotes', aggfunc='sum')

In [67]:
#Show the DataFrame
total_elections_df

party        DEMOCRAT  GREEN  LIBERTARIAN   OTHER  REPUBLICAN
county_name
ABBEVILLE      4101.0   23.0         88.0     6.0      8215.0
ACADIA         5443.0    NaN        241.0   145.0     22596.0
ACCOMACK       7578.0    NaN        188.0    12.0      9172.0
ADA          120539.0    NaN       5310.0  2841.0    130699.0
ADAIR          7687.0   47.0        314.0   128.0     22196.0
...               ...    ...          ...     ...         ...
YUBA          11230.0  124.0        510.0   256.0     17676.0
YUMA          32995.0    2.0       1189.0    35.0     40641.0
ZAPATA         1826.0    4.0         11.0     0.0      2033.0
ZAVALA         2864.0   12.0         13.0     0.0      1490.0
ZIEBACH         481.0    NaN         21.0     NaN       404.0

[1865 rows x 5 columns]

In [68]:
#Cleaning data in order to get the county name
debt_df['county_name'] =debt_df['NAME'].str.split(' ').str[0]
debt_df['county_name'] = debt_df['county_name'].str.upper()

/var/folders/hr/bqgkryq90tz9s1z4nh0ldql00000gn/T/ipykernel_71980/424965811.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  debt_df['county_name'] =debt_df['NAME'].str.split(' ').str[0]
/var/folders/hr/bqgkryq90tz9s1z4nh0ldql00000gn/T/ipykernel_71980/424965811.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  debt_df['county_name'] = debt_df['county_name'].str.upper()

In [69]:
#Checking null values in debt_df
debt_df['county_name'].isnull().sum()

0

In [70]:
#Cleaning data in order to get the county name
population_df['county_name'] = population_df['CTYNAME'].str.split(' ').str[0]
population_df['county_name'] = population_df['county_name'].str.upper()

/var/folders/hr/bqgkryq90tz9s1z4nh0ldql00000gn/T/ipykernel_71980/475299015.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  population_df['county_name'] = population_df['CTYNAME'].str.split(' ').str[0]
/var/folders/hr/bqgkryq90tz9s1z4nh0ldql00000gn/T/ipykernel_71980/475299015.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  population_df['county_name'] = population_df['county_name'].str.upper()

In [71]:
#Checking null values in debt_df
population_df['county_name'].isnull().sum()

0

In [72]:
#Showing the DataFrame
population_df

                CTYNAME  POPESTIMATE2019  INTERNATIONALMIG2019 county_name
0               Alabama          4903185                  2772     ALABAMA
1        Autauga County            55869                   -16     AUTAUGA
2        Baldwin County           223234                    80     BALDWIN
3        Barbour County            24686                    13     BARBOUR
4           Bibb County            22394                    10        BIBB
...                 ...              ...                   ...         ...
3188  Sweetwater County            42343                    23  SWEETWATER
3189       Teton County            23464                    79       TETON
3190       Uinta County            20226                     0       UINTA
3191    Washakie County             7805                    -5    WASHAKIE
3192      Weston County             6927                    18      WESTON

[3193 rows x 4 columns]

In [74]:
#Merge population and election datasets
poll_pop_df = pd.merge(total_elections_df, population_df, how ='left', on ='county_name')
poll_pop_df.head(20)

,county_name,DEMOCRAT,GREEN,LIBERTARIAN,OTHER,REPUBLICAN,CTYNAME,POPESTIMATE2019,INTERNATIONALMIG2019
0,ABBEVILLE,4101.0,23.0,88.0,6.0,8215.0,Abbeville County,24527.0,-11.0
1,ACADIA,5443.0,NaN,241.0,145.0,22596.0,Acadia Parish,62045.0,17.0
2,ACCOMACK,7578.0,NaN,188.0,12.0,9172.0,Accomack County,32316.0,30.0
3,ADA,120539.0,NaN,5310.0,2841.0,130699.0,Ada County,481587.0,26.0
4,ADAIR,7687.0,47.0,314.0,128.0,22196.0,Adair County,7152.0,2.0
5,ADAIR,7687.0,47.0,314.0,128.0,22196.0,Adair County,19202.0,-1.0
6,ADAIR,7687.0,47.0,314.0,128.0,22196.0,Adair County,25343.0,99.0
7,ADAIR,7687.0,47.0,314.0,128.0,22196.0,Adair County,22194.0,3.0
8,ADAMS,186146.0,875.0,6013.0,2678.0,209463.0,Adams County,517421.0,1204.0
9,ADAMS,186146.0,875.0,6013.0,2678.0,209463.0,Adams County,4294.0,1.0
10,ADAMS,186146.0,875.0,6013.0,2678.0,209463.0,Adams County,65435.0,18.0
11,ADAMS,186146.0,875.0,6013.0,2678.0,209463.0,Adams County,35777.0,8.0
12,ADAMS,186146.0,875.0,6013.0,2678.0,209463.0,Adams County,3602.0,0.0
13,ADAMS,186146.0,875.0,6013.0,2678.0,209463.0,Adams County,30693.0,151.0
14,ADAMS,186146.0,875.0,6013.0,2678.0,209463.0,Adams County,31363.0,59.0
15,ADAMS,186146.0,875.0,6013.0,2678.0,209463.0,Adams County,2216.0,6.0
16,ADAMS,186146.0,875.0,6013.0,2678.0,209463.0,Adams County,27698.0,5.0
17,ADAMS,186146.0,875.0,6013.0,2678.0,209463.0,Adams County,103009.0,54.0
18,ADAMS,186146.0,875.0,6013.0,2678.0,209463.0,Adams County,19983.0,24.0
19,ADAMS,186146.0,875.0,6013.0,2678.0,209463.0,Adams County,20220.0,8.0

In [92]:
#Merge all three datasets

final_df = pd.merge(poll_pop_df, debt_df, how='left', on = ['county_name'])
final_df

,county_name,DEMOCRAT,GREEN,LIBERTARIAN,OTHER,REPUBLICAN,CTYNAME,POPESTIMATE2019,INTERNATIONALMIG2019,NAME,"Share with Open Auto/Retail Debt, All","Share with Open Auto Debt, Communities of Color","Share with Open Auto Debt, Majority White Communities","Average household income, 2019 (ACS)","Average non-white household income, 2019 (ACS)","Average white, non-Hispanic household income, 2019 (ACS)"
0,ABBEVILLE,4101.0,23.0,88.0,6.0,8215.0,Abbeville County,24527.0,-11.0,"Abbeville County, South Carolina",0.3367609,n/a*,0.2151163,53822.0,37805,61259.0
1,ACADIA,5443.0,NaN,241.0,145.0,22596.0,Acadia Parish,62045.0,17.0,"Acadia Parish, Louisiana",0.4062176,n/a**,0.3034773,61465.0,36608,67627.0
2,ACCOMACK,7578.0,NaN,188.0,12.0,9172.0,Accomack County,32316.0,30.0,"Accomack County, Virginia",0.3315836,0.2742616,0.2801664,63100.0,49308,69458.0
3,ADA,120539.0,NaN,5310.0,2841.0,130699.0,Ada County,481587.0,26.0,"Ada County, Idaho",0.3555584,n/a**,0.3079475,96684.0,83899,98374.0
4,ADAIR,7687.0,47.0,314.0,128.0,22196.0,Adair County,7152.0,2.0,"Adair County, Iowa",0.3319149,n/a**,0.293617,68186.0,63343,68325.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15330,YUMA,32995.0,2.0,1189.0,35.0,40641.0,Yuma County,10019.0,47.0,"Yuma County, Arizona",0.3831791,0.3196924,0.2885118,59182.0,54724,65286.0
15331,YUMA,32995.0,2.0,1189.0,35.0,40641.0,Yuma County,10019.0,47.0,"Yuma County, Colorado",0.3959045,n/a**,0.3208191,68157.0,46145,72859.0
15332,ZAPATA,1826.0,4.0,11.0,0.0,2033.0,Zapata County,14179.0,-9.0,"Zapata County, Texas",0.3739837,0.2682927,n/a**,60551.0,60332,63099.0
15333,ZAVALA,2864.0,12.0,13.0,0.0,1490.0,Zavala County,11840.0,-2.0,"Zavala County, Texas",0.3901639,0.3125,n/a**,41014.0,40857,46127.0
15334,ZIEBACH,481.0,NaN,21.0,NaN,404.0,Ziebach County,2756.0,0.0,"Ziebach County, South Dakota",n/a*,n/a*,n/a**,52721.0,42990,73559.0

In [113]:
#Changing the Null values to numeric values to compare the columns
clean_df = final_df.fillna(value = 0, inplace=False)
clean_df

,county_name,DEMOCRAT,GREEN,LIBERTARIAN,OTHER,REPUBLICAN,CTYNAME,POPESTIMATE2019,INTERNATIONALMIG2019,NAME,"Share with Open Auto/Retail Debt, All","Share with Open Auto Debt, Communities of Color","Share with Open Auto Debt, Majority White Communities","Average household income, 2019 (ACS)","Average non-white household income, 2019 (ACS)","Average white, non-Hispanic household income, 2019 (ACS)"
0,ABBEVILLE,4101.0,23.0,88.0,6.0,8215.0,Abbeville County,24527.0,-11.0,"Abbeville County, South Carolina",0.3367609,n/a*,0.2151163,53822.0,37805,61259.0
1,ACADIA,5443.0,0.0,241.0,145.0,22596.0,Acadia Parish,62045.0,17.0,"Acadia Parish, Louisiana",0.4062176,n/a**,0.3034773,61465.0,36608,67627.0
2,ACCOMACK,7578.0,0.0,188.0,12.0,9172.0,Accomack County,32316.0,30.0,"Accomack County, Virginia",0.3315836,0.2742616,0.2801664,63100.0,49308,69458.0
3,ADA,120539.0,0.0,5310.0,2841.0,130699.0,Ada County,481587.0,26.0,"Ada County, Idaho",0.3555584,n/a**,0.3079475,96684.0,83899,98374.0
4,ADAIR,7687.0,47.0,314.0,128.0,22196.0,Adair County,7152.0,2.0,"Adair County, Iowa",0.3319149,n/a**,0.293617,68186.0,63343,68325.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15330,YUMA,32995.0,2.0,1189.0,35.0,40641.0,Yuma County,10019.0,47.0,"Yuma County, Arizona",0.3831791,0.3196924,0.2885118,59182.0,54724,65286.0
15331,YUMA,32995.0,2.0,1189.0,35.0,40641.0,Yuma County,10019.0,47.0,"Yuma County, Colorado",0.3959045,n/a**,0.3208191,68157.0,46145,72859.0
15332,ZAPATA,1826.0,4.0,11.0,0.0,2033.0,Zapata County,14179.0,-9.0,"Zapata County, Texas",0.3739837,0.2682927,n/a**,60551.0,60332,63099.0
15333,ZAVALA,2864.0,12.0,13.0,0.0,1490.0,Zavala County,11840.0,-2.0,"Zavala County, Texas",0.3901639,0.3125,n/a**,41014.0,40857,46127.0
15334,ZIEBACH,481.0,0.0,21.0,0.0,404.0,Ziebach County,2756.0,0.0,"Ziebach County, South Dakota",n/a*,n/a*,n/a**,52721.0,42990,73559.0

In [119]:
#Creating the winner column in order to know which party won
clean_df['winner'] = np.where((clean_df['DEMOCRAT'] > clean_df['REPUBLICAN']), 'DEMOCRAT', 0)

In [120]:
#Showing the dataset
clean_df

,county_name,DEMOCRAT,GREEN,LIBERTARIAN,OTHER,REPUBLICAN,CTYNAME,POPESTIMATE2019,INTERNATIONALMIG2019,NAME,"Share with Open Auto/Retail Debt, All","Share with Open Auto Debt, Communities of Color","Share with Open Auto Debt, Majority White Communities","Average household income, 2019 (ACS)","Average non-white household income, 2019 (ACS)","Average white, non-Hispanic household income, 2019 (ACS)",winner
0,ABBEVILLE,4101.0,23.0,88.0,6.0,8215.0,Abbeville County,24527.0,-11.0,"Abbeville County, South Carolina",0.3367609,n/a*,0.2151163,53822.0,37805,61259.0,0
1,ACADIA,5443.0,0.0,241.0,145.0,22596.0,Acadia Parish,62045.0,17.0,"Acadia Parish, Louisiana",0.4062176,n/a**,0.3034773,61465.0,36608,67627.0,0
2,ACCOMACK,7578.0,0.0,188.0,12.0,9172.0,Accomack County,32316.0,30.0,"Accomack County, Virginia",0.3315836,0.2742616,0.2801664,63100.0,49308,69458.0,0
3,ADA,120539.0,0.0,5310.0,2841.0,130699.0,Ada County,481587.0,26.0,"Ada County, Idaho",0.3555584,n/a**,0.3079475,96684.0,83899,98374.0,0
4,ADAIR,7687.0,47.0,314.0,128.0,22196.0,Adair County,7152.0,2.0,"Adair County, Iowa",0.3319149,n/a**,0.293617,68186.0,63343,68325.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15330,YUMA,32995.0,2.0,1189.0,35.0,40641.0,Yuma County,10019.0,47.0,"Yuma County, Arizona",0.3831791,0.3196924,0.2885118,59182.0,54724,65286.0,0
15331,YUMA,32995.0,2.0,1189.0,35.0,40641.0,Yuma County,10019.0,47.0,"Yuma County, Colorado",0.3959045,n/a**,0.3208191,68157.0,46145,72859.0,0
15332,ZAPATA,1826.0,4.0,11.0,0.0,2033.0,Zapata County,14179.0,-9.0,"Zapata County, Texas",0.3739837,0.2682927,n/a**,60551.0,60332,63099.0,0
15333,ZAVALA,2864.0,12.0,13.0,0.0,1490.0,Zavala County,11840.0,-2.0,"Zavala County, Texas",0.3901639,0.3125,n/a**,41014.0,40857,46127.0,DEMOCRAT
15334,ZIEBACH,481.0,0.0,21.0,0.0,404.0,Ziebach County,2756.0,0.0,"Ziebach County, South Dakota",n/a*,n/a*,n/a**,52721.0,42990,73559.0,DEMOCRAT

In [123]:
#Transforming the integer values to numeric values
clean_df[['Share with Open Auto/Retail Debt, All', 'Share with Open Auto Debt, Communities of Color', 'Share with Open Auto Debt, Majority White Communities']] = clean_df[['Share with Open Auto/Retail Debt, All', 'Share with Open Auto Debt, Communities of Color', 'Share with Open Auto Debt, Majority White Communities']].replace(to_replace = ['n/a*', 'n/a**'], value=0).astype(float)

clean_df.dtypes

county_name                                                  object
DEMOCRAT                                                    float64
GREEN                                                       float64
LIBERTARIAN                                                 float64
OTHER                                                       float64
REPUBLICAN                                                  float64
CTYNAME                                                      object
POPESTIMATE2019                                             float64
INTERNATIONALMIG2019                                        float64
NAME                                                         object
Share with Open Auto/Retail Debt, All                       float64
Share with Open Auto Debt, Communities of Color             float64
Share with Open Auto Debt, Majority White Communities       float64
Average household income, 2019 (ACS)                        float64
Average non-white household income, 2019 (ACS)               object
Average white, non-Hispanic household income, 2019 (ACS)    float64
winner                                                       object
dtype: object

In [124]:
#Multiplying population to total debt
clean_df['Share with Open Auto/Retail Debt, All'] = clean_df['Share with Open Auto/Retail Debt, All']*clean_df['POPESTIMATE2019']

In [125]:
#Multiplying population to debt in communities of color
clean_df['Share with Open Auto Debt, Communities of Color'] = clean_df['Share with Open Auto Debt, Communities of Color']*clean_df['POPESTIMATE2019']

In [126]:
# Multiplying population to debt in white communities
clean_df['Share with Open Auto Debt, Majority White Communities'] = clean_df['Share with Open Auto Debt, Majority White Communities']*clean_df['POPESTIMATE2019']

In [127]:
#Drop the final columns that are not needed
clean_df = clean_df.drop(columns=['CTYNAME','NAME'])

In [129]:
#Add the 50 people that were considered as null values in the polls
clean_df[['Share with Open Auto/Retail Debt, All', 'Share with Open Auto Debt, Communities of Color', 'Share with Open Auto Debt, Majority White Communities']] = clean_df[['Share with Open Auto/Retail Debt, All', 'Share with Open Auto Debt, Communities of Color', 'Share with Open Auto Debt, Majority White Communities']].replace(to_replace = 0, value=50).astype(float)

In [130]:
#Show the DataFrame
clean_df

,county_name,DEMOCRAT,GREEN,LIBERTARIAN,OTHER,REPUBLICAN,POPESTIMATE2019,INTERNATIONALMIG2019,"Share with Open Auto/Retail Debt, All","Share with Open Auto Debt, Communities of Color","Share with Open Auto Debt, Majority White Communities","Average household income, 2019 (ACS)","Average non-white household income, 2019 (ACS)","Average white, non-Hispanic household income, 2019 (ACS)",winner
0,ABBEVILLE,4101.0,23.0,88.0,6.0,8215.0,24527.0,-11.0,8259.734594,50.000000,5276.157490,53822.0,37805,61259.0,0
1,ACADIA,5443.0,0.0,241.0,145.0,22596.0,62045.0,17.0,25203.770992,50.000000,18829.249079,61465.0,36608,67627.0,0
2,ACCOMACK,7578.0,0.0,188.0,12.0,9172.0,32316.0,30.0,10715.455618,8863.037866,9053.857382,63100.0,49308,69458.0,0
3,ADA,120539.0,0.0,5310.0,2841.0,130699.0,481587.0,26.0,171232.303181,50.000000,148303.512683,96684.0,83899,98374.0,0
4,ADAIR,7687.0,47.0,314.0,128.0,22196.0,7152.0,2.0,2373.855365,50.000000,2099.948784,68186.0,63343,68325.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15330,YUMA,32995.0,2.0,1189.0,35.0,40641.0,10019.0,47.0,3839.071403,3202.998156,2890.599724,59182.0,54724,65286.0,0
15331,YUMA,32995.0,2.0,1189.0,35.0,40641.0,10019.0,47.0,3966.567186,50.000000,3214.286563,68157.0,46145,72859.0,0
15332,ZAPATA,1826.0,4.0,11.0,0.0,2033.0,14179.0,-9.0,5302.714882,3804.122193,50.000000,60551.0,60332,63099.0,0
15333,ZAVALA,2864.0,12.0,13.0,0.0,1490.0,11840.0,-2.0,4619.540576,3700.000000,50.000000,41014.0,40857,46127.0,DEMOCRAT
15334,ZIEBACH,481.0,0.0,21.0,0.0,404.0,2756.0,0.0,50.000000,50.000000,50.000000,52721.0,42990,73559.0,DEMOCRAT

In [131]:
clean_df.isnull().sum()

county_name                                                 0
DEMOCRAT                                                    0
GREEN                                                       0
LIBERTARIAN                                                 0
OTHER                                                       0
REPUBLICAN                                                  0
POPESTIMATE2019                                             0
INTERNATIONALMIG2019                                        0
Share with Open Auto/Retail Debt, All                       0
Share with Open Auto Debt, Communities of Color             0
Share with Open Auto Debt, Majority White Communities       0
Average household income, 2019 (ACS)                        0
Average non-white household income, 2019 (ACS)              0
Average white, non-Hispanic household income, 2019 (ACS)    0
winner                                                      0
dtype: int64

In [ ]:
clean_df.to_csv('prueba.csv')