In [3]:
#import libraries

import pandas as pd

In [4]:
county_elections_df = pd.read_csv('Resources/countypres_2000-2020.csv')
county_elections_df.head()

,year,state,state_po,county_name,county_fips,office,candidate,party,candidatevotes,totalvotes,version,mode
0,2000,ALABAMA,AL,AUTAUGA,1001.0,US PRESIDENT,AL GORE,DEMOCRAT,4942,17208,20220315,TOTAL
1,2000,ALABAMA,AL,AUTAUGA,1001.0,US PRESIDENT,GEORGE W. BUSH,REPUBLICAN,11993,17208,20220315,TOTAL
2,2000,ALABAMA,AL,AUTAUGA,1001.0,US PRESIDENT,RALPH NADER,GREEN,160,17208,20220315,TOTAL
3,2000,ALABAMA,AL,AUTAUGA,1001.0,US PRESIDENT,OTHER,OTHER,113,17208,20220315,TOTAL
4,2000,ALABAMA,AL,BALDWIN,1003.0,US PRESIDENT,AL GORE,DEMOCRAT,13997,56480,20220315,TOTAL

In [5]:
county_elections_df.dtypes

year                int64
state              object
state_po           object
county_name        object
county_fips       float64
office             object
candidate          object
party              object
candidatevotes      int64
totalvotes          int64
version             int64
mode               object
dtype: object

In [6]:
population_county_df = pd.read_csv('Resources/co-est2019-alldata.csv', encoding_errors='ignore')
population_county_df

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2019,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015,RNETMIG2016,RNETMIG2017,RNETMIG2018,RNETMIG2019
0,40,3,6,1,0,Alabama,Alabama,4779736,4780125,4785437,...,1.917501,0.578434,1.186314,1.522549,0.563489,0.626357,0.745172,1.090366,1.773786,2.483744
1,50,3,6,1,1,Alabama,Autauga County,54571,54597,54773,...,4.847310,6.018182,-6.226119,-3.902226,1.970443,-1.712875,4.777171,0.849656,0.540916,4.560062
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183112,...,24.017829,16.641870,17.488579,22.751474,20.184334,17.725964,21.279291,22.398256,24.727215,24.380567
3,50,3,6,1,5,Alabama,Barbour County,27457,27455,27327,...,-5.690302,0.292676,-6.897817,-8.132185,-5.140431,-15.724575,-18.238016,-24.998528,-8.754922,-5.165664
4,50,3,6,1,7,Alabama,Bibb County,22915,22915,22870,...,1.385134,-4.998356,-3.787545,-5.797999,1.331144,1.329817,-0.708717,-3.234669,-6.857092,1.831952
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,50,4,8,56,37,Wyoming,Sweetwater County,43806,43806,43574,...,-17.605427,0.502513,15.035735,-4.614071,-13.140225,-13.762031,-18.484164,-23.515727,-18.743773,-17.065527
3189,50,4,8,56,39,Wyoming,Teton County,21294,21298,21296,...,-1.583464,-2.575509,1.905293,23.259519,12.508872,4.670450,1.253214,-0.171608,-12.432212,1.797445
3190,50,4,8,56,41,Wyoming,Uinta County,21118,21121,21089,...,-9.181105,-18.196975,-4.487730,-10.870861,-15.033634,-10.484550,-11.485101,-18.923455,-13.554993,-9.181105
3191,50,4,8,56,43,Wyoming,Washakie County,8533,8528,8530,...,-7.652085,-12.839390,-3.084589,-1.307811,-18.938032,0.000000,-15.204038,-15.950541,-17.246806,-8.289759
3192,50,4,8,56,45,Wyoming,Weston County,7208,7208,7198,...,0.000000,-9.065551,-10.549265,6.191515,0.420345,9.201171,0.693097,-36.227798,-6.910452,2.599090

In [ ]:
population_county_df

In [59]:
Debt_data_df = pd.read_csv('Resources/debt.csv')

Debt_data_df

,NAME,GEOID,state_name,"Auto/Retail Debt Delinquency Rate, All","Auto/Retail Debt Delinquency Rate, Communities of Color","Auto/Retail Debt Delinquency Rate, Majority White Communities","Share of Subprime Consumers with Auto/Retail Delinquencies, All","Share of Near-Prime Consumers with Auto/Retail Delinquencies, All","Share of Prime Consumers with Auto/Retail Delinquencies, All","Share with Open Auto Debt, All","Share with Open Auto Debt, Communities of Color","Share with Open Auto Debt, Majority White Communities","Share with Open Auto/Retail Debt, All","Share with Open Auto/Retail Debt, Communities of Color","Share with Open Auto/Retail Debt, Majority White Communities","% population in rural areas, 2010 (Census)",poc_pct,"Average household income, 2019 (ACS)","Average non-white household income, 2019 (ACS)","Average white, non-Hispanic household income, 2019 (ACS)"
0,"Autauga County, Alabama",1001,Alabama,0.0634218,n/a*,0.0650155,0.2628205,0.0130719,0,0.2623955,n/a*,0.2649472,0.3727019,n/a*,0.3733881,0.420022,0.253973,75326,50809,82971
1,"Baldwin County, Alabama",1003,Alabama,0.0428429,n/a**,0.0427753,0.2402464,0.0205339,0.0004912,0.33154,n/a**,0.3327853,0.3993275,n/a**,0.4010139,0.422791,0.169276,81449,47333,86522
2,"Barbour County, Alabama",1005,Alabama,0.0868167,n/a*,n/a*,0.297619,0.015873,0,0.2787958,0.2435897,0.3454545,0.3979058,0.2948718,0.4181818,0.677896,0.541895,47068,31673,63382
3,"Bibb County, Alabama",1007,Alabama,0.1048689,n/a**,0.0917031,0.3246753,n/a*,0,0.3047619,n/a**,0.3118081,0.4111111,n/a**,0.4095941,0.683526,0.254746,60182,40249,65273
4,"Blount County, Alabama",1009,Alabama,0.0407876,n/a*,0.0407876,0.1746988,0,0,0.2988116,n/a*,0.2989807,0.3978495,n/a*,0.3980747,0.899515,0.131066,65639,49595,67146
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3132,"Sweetwater County, Wyoming",56037,Wyoming,0.042735,n/a**,0.0434783,0.25,0.0163934,0,0.4200164,n/a**,0.4255499,0.4757998,n/a**,0.4822335,0.109163,0.204430,85346,64674,89540
3133,"Teton County, Wyoming",56039,Wyoming,0.0040984,n/a**,0.005814,n/a*,n/a*,0,0.2642424,n/a**,0.2479609,0.2957576,n/a**,0.2805873,0.464309,0.186641,132531,71564,141299
3134,"Uinta County, Wyoming",56041,Wyoming,0.0283688,n/a**,0.0290909,n/a*,n/a*,0,0.4119658,n/a**,0.4179894,0.4820513,n/a**,0.4850088,0.430959,0.124811,74938,72010,75273
3135,"Washakie County, Wyoming",56043,Wyoming,0.0123457,n/a**,0.0123457,n/a*,n/a*,0,0.2627451,n/a**,0.2627451,0.3176471,n/a**,0.3176471,0.359545,0.181014,65496,56047,67192
3136,"Weston County, Wyoming",56045,Wyoming,0.019802,n/a**,0.019802,n/a*,n/a*,0,0.387931,n/a**,0.3896104,0.4353448,n/a**,0.4372294,0.545366,0.036317,68877,37509,69485

In [6]:
county_elections.dtypes

year                int64
state              object
state_po           object
county_name        object
county_fips       float64
office             object
candidate          object
party              object
candidatevotes      int64
totalvotes          int64
version             int64
mode               object
dtype: object

In [7]:
len(county_elections)

72617

In [10]:
county_elections.state.value_counts()

TEXAS                   5334
GEORGIA                 4452
VIRGINIA                3736
NORTH CAROLINA          3600
ARKANSAS                2700
IOWA                    2574
MISSOURI                2436
KENTUCKY                2400
OKLAHOMA                2156
ILLINOIS                2142
SOUTH CAROLINA          2116
KANSAS                  1995
INDIANA                 1932
MINNESOTA               1827
TENNESSEE               1805
NEBRASKA                1767
OHIO                    1760
MICHIGAN                1743
MISSISSIPPI             1722
WISCONSIN               1512
FLORIDA                 1407
COLORADO                1340
NEW YORK                1302
LOUISIANA               1280
ALABAMA                 1273
PENNSYLVANIA            1273
SOUTH DAKOTA            1254
CALIFORNIA              1218
WEST VIRGINIA           1100
MONTANA                 1064
NORTH DAKOTA            1060
UTAH                    1039
MARYLAND                 984
IDAHO                    880
ALASKA                   861
WASHINGTON               819
OREGON                   756
NEW MEXICO               693
ARIZONA                  465
WYOMING                  460
NEW JERSEY               441
MAINE                    352
NEVADA                   340
MASSACHUSETTS            294
VERMONT                  294
NEW HAMPSHIRE            190
CONNECTICUT              184
RHODE ISLAND             120
HAWAII                    84
DELAWARE                  60
DISTRICT OF COLUMBIA      21
Name: state, dtype: int64

In [11]:
county_elections.county_name.value_counts()

WASHINGTON           727
FRANKLIN             576
JEFFERSON            563
JACKSON              541
LINCOLN              532
                    ...
HAMPTON CITY          12
HARRISONBURG CITY     12
WINCHESTER CITY       12
NORTON CITY            8
OGLALA LAKOTA          6
Name: county_name, Length: 1892, dtype: int64

In [12]:
len(county_elections.county_name.unique())

1892

In [13]:
len(county_elections.state.unique())

51

In [14]:
county_elections.party.value_counts()

DEMOCRAT       20906
REPUBLICAN     20906
OTHER          19815
GREEN           6035
LIBERTARIAN     4955
Name: party, dtype: int64

In [10]:
print(population_county_df.columns)

Index(['SUMLEV', 'REGION', 'DIVISION', 'STATE', 'COUNTY', 'STNAME', 'CTYNAME',
       'CENSUS2010POP', 'ESTIMATESBASE2010', 'POPESTIMATE2010',
       ...
       'RDOMESTICMIG2019', 'RNETMIG2011', 'RNETMIG2012', 'RNETMIG2013',
       'RNETMIG2014', 'RNETMIG2015', 'RNETMIG2016', 'RNETMIG2017',
       'RNETMIG2018', 'RNETMIG2019'],
      dtype='object', length=164)

In [13]:
#Drop Columns that are not usable in the data sets

population_df = population_county_df[['CTYNAME','POPESTIMATE2019','INTERNATIONALMIG2019']]
population_df

                CTYNAME  POPESTIMATE2019  INTERNATIONALMIG2019
0               Alabama          4903185                  2772
1        Autauga County            55869                   -16
2        Baldwin County           223234                    80
3        Barbour County            24686                    13
4           Bibb County            22394                    10
...                 ...              ...                   ...
3188  Sweetwater County            42343                    23
3189       Teton County            23464                    79
3190       Uinta County            20226                     0
3191    Washakie County             7805                    -5
3192      Weston County             6927                    18

[3193 rows x 3 columns]

In [115]:
debt_df = Debt_data_df[['NAME','Share with Open Auto/Retail Debt, All', 'Share with Open Auto Debt, Communities of Color', 'Share with Open Auto Debt, Majority White Communities', 'Average household income, 2019 (ACS)', 'Average non-white household income, 2019 (ACS)', 'Average white, non-Hispanic household income, 2019 (ACS)']]
debt_df

,NAME,"Share with Open Auto/Retail Debt, All","Share with Open Auto Debt, Communities of Color","Share with Open Auto Debt, Majority White Communities","Average household income, 2019 (ACS)","Average non-white household income, 2019 (ACS)","Average white, non-Hispanic household income, 2019 (ACS)"
0,"Autauga County, Alabama",0.3727019,n/a*,0.2649472,75326,50809,82971
1,"Baldwin County, Alabama",0.3993275,n/a**,0.3327853,81449,47333,86522
2,"Barbour County, Alabama",0.3979058,0.2435897,0.3454545,47068,31673,63382
3,"Bibb County, Alabama",0.4111111,n/a**,0.3118081,60182,40249,65273
4,"Blount County, Alabama",0.3978495,n/a*,0.2989807,65639,49595,67146
...,...,...,...,...,...,...,...
3132,"Sweetwater County, Wyoming",0.4757998,n/a**,0.4255499,85346,64674,89540
3133,"Teton County, Wyoming",0.2957576,n/a**,0.2479609,132531,71564,141299
3134,"Uinta County, Wyoming",0.4820513,n/a**,0.4179894,74938,72010,75273
3135,"Washakie County, Wyoming",0.3176471,n/a**,0.2627451,65496,56047,67192
3136,"Weston County, Wyoming",0.4353448,n/a**,0.3896104,68877,37509,69485

In [17]:
elections_df = county_elections_df.drop(columns = ['office', 'candidate', 'totalvotes', 'version', 'mode'])
elections_df

,year,state,state_po,county_name,county_fips,party,candidatevotes
0,2000,ALABAMA,AL,AUTAUGA,1001.0,DEMOCRAT,4942
1,2000,ALABAMA,AL,AUTAUGA,1001.0,REPUBLICAN,11993
2,2000,ALABAMA,AL,AUTAUGA,1001.0,GREEN,160
3,2000,ALABAMA,AL,AUTAUGA,1001.0,OTHER,113
4,2000,ALABAMA,AL,BALDWIN,1003.0,DEMOCRAT,13997
...,...,...,...,...,...,...,...
72612,2020,WYOMING,WY,WASHAKIE,56043.0,REPUBLICAN,3245
72613,2020,WYOMING,WY,WESTON,56045.0,DEMOCRAT,360
72614,2020,WYOMING,WY,WESTON,56045.0,LIBERTARIAN,46
72615,2020,WYOMING,WY,WESTON,56045.0,OTHER,47
72616,2020,WYOMING,WY,WESTON,56045.0,REPUBLICAN,3107

In [116]:
debt_df['county_name'] =debt_df['NAME'].str.split(' ').str[0]
debt_df['county_name'] = debt_df['county_name'].str.upper()

/var/folders/hr/bqgkryq90tz9s1z4nh0ldql00000gn/T/ipykernel_45789/424965811.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  debt_df['county_name'] =debt_df['NAME'].str.split(' ').str[0]
/var/folders/hr/bqgkryq90tz9s1z4nh0ldql00000gn/T/ipykernel_45789/424965811.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  debt_df['county_name'] = debt_df['county_name'].str.upper()

In [97]:
debt_df['county'].isnull().sum()

0

In [105]:
population_df['county_name'] = population_df['CTYNAME'].str.split(' ').str[0]
population_df['county_name'] = population_df['county_name'].str.upper()

/var/folders/hr/bqgkryq90tz9s1z4nh0ldql00000gn/T/ipykernel_45789/3845031733.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  population_df['county_name'] = population_df['CTYNAME'].str.split(' ').str[0]
/var/folders/hr/bqgkryq90tz9s1z4nh0ldql00000gn/T/ipykernel_45789/3845031733.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  population_df['county_name'] = population_df['county_name'].str.upper()

In [99]:
population_df['county'].isnull().sum()

0

In [106]:
poll_pop_df = pd.merge(elections_df,population_df, how = 'left', on =['county_name'])
poll_pop_df

,year,state,state_po,county_name,county_fips,party,candidatevotes,CTYNAME,POPESTIMATE2019,INTERNATIONALMIG2019,county
0,2000,ALABAMA,AL,AUTAUGA,1001.0,DEMOCRAT,4942,Autauga County,55869.0,-16.0,Autauga
1,2000,ALABAMA,AL,AUTAUGA,1001.0,REPUBLICAN,11993,Autauga County,55869.0,-16.0,Autauga
2,2000,ALABAMA,AL,AUTAUGA,1001.0,GREEN,160,Autauga County,55869.0,-16.0,Autauga
3,2000,ALABAMA,AL,AUTAUGA,1001.0,OTHER,113,Autauga County,55869.0,-16.0,Autauga
4,2000,ALABAMA,AL,BALDWIN,1003.0,DEMOCRAT,13997,Baldwin County,223234.0,80.0,Baldwin
...,...,...,...,...,...,...,...,...,...,...,...
346207,2020,WYOMING,WY,WASHAKIE,56043.0,REPUBLICAN,3245,Washakie County,7805.0,-5.0,Washakie
346208,2020,WYOMING,WY,WESTON,56045.0,DEMOCRAT,360,Weston County,6927.0,18.0,Weston
346209,2020,WYOMING,WY,WESTON,56045.0,LIBERTARIAN,46,Weston County,6927.0,18.0,Weston
346210,2020,WYOMING,WY,WESTON,56045.0,OTHER,47,Weston County,6927.0,18.0,Weston
346211,2020,WYOMING,WY,WESTON,56045.0,REPUBLICAN,3107,Weston County,6927.0,18.0,Weston

In [117]:
final_df = pd.merge(poll_pop_df, debt_df, how='left', on = ['county_name'])
final_df

,year,state,state_po,county_name,county_fips,party,candidatevotes,CTYNAME,POPESTIMATE2019,INTERNATIONALMIG2019,county,NAME,"Share with Open Auto/Retail Debt, All","Share with Open Auto Debt, Communities of Color","Share with Open Auto Debt, Majority White Communities","Average household income, 2019 (ACS)","Average non-white household income, 2019 (ACS)","Average white, non-Hispanic household income, 2019 (ACS)"
0,2000,ALABAMA,AL,AUTAUGA,1001.0,DEMOCRAT,4942,Autauga County,55869.0,-16.0,Autauga,"Autauga County, Alabama",0.3727019,n/a*,0.2649472,75326.0,50809,82971.0
1,2000,ALABAMA,AL,AUTAUGA,1001.0,REPUBLICAN,11993,Autauga County,55869.0,-16.0,Autauga,"Autauga County, Alabama",0.3727019,n/a*,0.2649472,75326.0,50809,82971.0
2,2000,ALABAMA,AL,AUTAUGA,1001.0,GREEN,160,Autauga County,55869.0,-16.0,Autauga,"Autauga County, Alabama",0.3727019,n/a*,0.2649472,75326.0,50809,82971.0
3,2000,ALABAMA,AL,AUTAUGA,1001.0,OTHER,113,Autauga County,55869.0,-16.0,Autauga,"Autauga County, Alabama",0.3727019,n/a*,0.2649472,75326.0,50809,82971.0
4,2000,ALABAMA,AL,BALDWIN,1003.0,DEMOCRAT,13997,Baldwin County,223234.0,80.0,Baldwin,"Baldwin County, Alabama",0.3993275,n/a**,0.3327853,81449.0,47333,86522.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4566198,2020,WYOMING,WY,WASHAKIE,56043.0,REPUBLICAN,3245,Washakie County,7805.0,-5.0,Washakie,"Washakie County, Wyoming",0.3176471,n/a**,0.2627451,65496.0,56047,67192.0
4566199,2020,WYOMING,WY,WESTON,56045.0,DEMOCRAT,360,Weston County,6927.0,18.0,Weston,"Weston County, Wyoming",0.4353448,n/a**,0.3896104,68877.0,37509,69485.0
4566200,2020,WYOMING,WY,WESTON,56045.0,LIBERTARIAN,46,Weston County,6927.0,18.0,Weston,"Weston County, Wyoming",0.4353448,n/a**,0.3896104,68877.0,37509,69485.0
4566201,2020,WYOMING,WY,WESTON,56045.0,OTHER,47,Weston County,6927.0,18.0,Weston,"Weston County, Wyoming",0.4353448,n/a**,0.3896104,68877.0,37509,69485.0
4566202,2020,WYOMING,WY,WESTON,56045.0,REPUBLICAN,3107,Weston County,6927.0,18.0,Weston,"Weston County, Wyoming",0.4353448,n/a**,0.3896104,68877.0,37509,69485.0

In [135]:
final_df[['Share with Open Auto/Retail Debt, All', 'Share with Open Auto Debt, Communities of Color', 'Share with Open Auto Debt, Majority White Communities']] = final_df[['Share with Open Auto/Retail Debt, All', 'Share with Open Auto Debt, Communities of Color', 'Share with Open Auto Debt, Majority White Communities']].replace(to_replace = ['n/a*', 'n/a**'], value=0).astype(float)

final_df.dtypes

year                                                          int64
state                                                        object
state_po                                                     object
county_name                                                  object
county_fips                                                 float64
party                                                        object
candidatevotes                                                int64
CTYNAME                                                      object
POPESTIMATE2019                                             float64
INTERNATIONALMIG2019                                        float64
county                                                       object
NAME                                                         object
Share with Open Auto/Retail Debt, All                       float64
Share with Open Auto Debt, Communities of Color             float64
Share with Open Auto Debt, Majority White Communities       float64
Average household income, 2019 (ACS)                        float64
Average non-white household income, 2019 (ACS)               object
Average white, non-Hispanic household income, 2019 (ACS)    float64
dtype: object

In [137]:
final_df['Share with Open Auto/Retail Debt, All'] = final_df['Share with Open Auto/Retail Debt, All']*final_df['POPESTIMATE2019']

In [139]:
final_df['Share with Open Auto Debt, Communities of Color'] = final_df['Share with Open Auto Debt, Communities of Color']*final_df['POPESTIMATE2019']

In [140]:
final_df['Share with Open Auto Debt, Majority White Communities'] = final_df['Share with Open Auto Debt, Majority White Communities']*final_df['POPESTIMATE2019']

In [144]:
final1_df = final_df.drop(columns=['CTYNAME','county','NAME'])

In [146]:
final1_df[['Share with Open Auto/Retail Debt, All', 'Share with Open Auto Debt, Communities of Color', 'Share with Open Auto Debt, Majority White Communities']] = final1_df[['Share with Open Auto/Retail Debt, All', 'Share with Open Auto Debt, Communities of Color', 'Share with Open Auto Debt, Majority White Communities']].replace(to_replace = 0, value=50).astype(float)

In [164]:
final1_df = final1_df[final1_df['year'] == 2020]
final1_df

,year,state,state_po,county_name,county_fips,party,candidatevotes,POPESTIMATE2019,INTERNATIONALMIG2019,"Share with Open Auto/Retail Debt, All","Share with Open Auto Debt, Communities of Color","Share with Open Auto Debt, Majority White Communities","Average household income, 2019 (ACS)","Average non-white household income, 2019 (ACS)","Average white, non-Hispanic household income, 2019 (ACS)"
3219196,2020,ALABAMA,AL,AUTAUGA,1001.0,DEMOCRAT,7503,55869.0,-16.0,20822.482451,50.0,14802.335117,75326.0,50809,82971.0
3219197,2020,ALABAMA,AL,AUTAUGA,1001.0,OTHER,429,55869.0,-16.0,20822.482451,50.0,14802.335117,75326.0,50809,82971.0
3219198,2020,ALABAMA,AL,AUTAUGA,1001.0,REPUBLICAN,19838,55869.0,-16.0,20822.482451,50.0,14802.335117,75326.0,50809,82971.0
3219199,2020,ALABAMA,AL,BALDWIN,1003.0,DEMOCRAT,24578,223234.0,80.0,89143.475135,50.0,74288.993660,81449.0,47333,86522.0
3219200,2020,ALABAMA,AL,BALDWIN,1003.0,DEMOCRAT,24578,223234.0,80.0,92137.601160,50.0,54755.505222,56958.0,49055,63124.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4566198,2020,WYOMING,WY,WASHAKIE,56043.0,REPUBLICAN,3245,7805.0,-5.0,2479.235616,50.0,2050.725506,65496.0,56047,67192.0
4566199,2020,WYOMING,WY,WESTON,56045.0,DEMOCRAT,360,6927.0,18.0,3015.633430,50.0,2698.831241,68877.0,37509,69485.0
4566200,2020,WYOMING,WY,WESTON,56045.0,LIBERTARIAN,46,6927.0,18.0,3015.633430,50.0,2698.831241,68877.0,37509,69485.0
4566201,2020,WYOMING,WY,WESTON,56045.0,OTHER,47,6927.0,18.0,3015.633430,50.0,2698.831241,68877.0,37509,69485.0
4566202,2020,WYOMING,WY,WESTON,56045.0,REPUBLICAN,3107,6927.0,18.0,3015.633430,50.0,2698.831241,68877.0,37509,69485.0

In [169]:
#Declare a new list to encounter the candidates

party_options = []

#Declare a dictionary in which we will have the votes for each candidate

party_votes = {}

state_options = []

#print each row in the csv file
for index, row in final1_df.iterrows():
    
    state_name = row['state']
    
    if state_name not in state_options:

        #add the total vote count

        total_votes = row['candidatevotes']

        #Find the candidates that ran in the election

        party_name = row['party']

        #Add it to the list of candidates
        if party_name not in party_options:
            #add candidate name to candidates list
            party_options.append(party_name)
            #Begin tracking that candidates vote count
            party_votes[party_name] = 0
            party_votes[party_name] = total_votes
            
        state_options.append(state_name)

In [170]:
party_votes

{'DEMOCRAT': 7503}

In [171]:
party_options

['DEMOCRAT']

In [165]:
final1_df['party'].value_counts()

DEMOCRAT       311093
REPUBLICAN     311093
LIBERTARIAN    295694
OTHER          246514
GREEN          182613
Name: party, dtype: int64

In [168]:
state_options

['ALABAMA',
 'ALASKA',
 'ARIZONA',
 'ARKANSAS',
 'CALIFORNIA',
 'COLORADO',
 'CONNECTICUT',
 'DELAWARE',
 'DISTRICT OF COLUMBIA',
 'FLORIDA',
 'GEORGIA',
 'HAWAII',
 'IDAHO',
 'ILLINOIS',
 'INDIANA',
 'IOWA',
 'KANSAS',
 'KENTUCKY',
 'LOUISIANA',
 'MAINE',
 'MICHIGAN',
 'MINNESOTA',
 'MISSISSIPPI',
 'MISSOURI',
 'NEVADA',
 'NEW HAMPSHIRE',
 'NEW JERSEY',
 'NEW MEXICO',
 'NEW YORK',
 'NORTH CAROLINA',
 'NORTH DAKOTA',
 'OREGON',
 'PENNSYLVANIA',
 'RHODE ISLAND',
 'SOUTH CAROLINA',
 'TEXAS',
 'VERMONT',
 'WEST VIRGINIA',
 'MARYLAND',
 'MASSACHUSETTS',
 'MONTANA',
 'NEBRASKA',
 'OHIO',
 'OKLAHOMA',
 'SOUTH DAKOTA',
 'TENNESSEE',
 'UTAH',
 'VIRGINIA',
 'WASHINGTON',
 'WISCONSIN',
 'WYOMING']