# Final Project Data : Exploratory Analysis

In [1]:
# Add our dependencies.
import csv
import os

In [68]:
# Add our dependencies.
import pandas as pd
import numpy as np
import sqlalchemy as sql
from sqlalchemy import create_engine
import psycopg2
from sqlalchemy import MetaData

# Loading files

In [3]:
county_elections_to_load = 'https://dataanalyticsfinalproject2022.s3.us-east-2.amazonaws.com/Resources/countypres_2000-2020.csv'
debt_to_load= "https://dataanalyticsfinalproject2022.s3.us-east-2.amazonaws.com/Resources/county_dia_auto_+7+Jun+2022.csv"
pop_to_load= "https://dataanalyticsfinalproject2022.s3.us-east-2.amazonaws.com/Resources/co-est2019-alldata.csv"

# Postgres Connection

In [6]:
engine = sql.create_engine('postgresql://ElectionTeam:finalproject@final-data-project.cxtxzq2kyq9u.us-east-1.rds.amazonaws.com:5432/election_data')

In [7]:
engine.table_names()

[]

# DEBT BY COUNTY DATABASE

In [8]:
debt_data_df=pd.read_csv(debt_to_load, header=1)
debt_data_df.head()

,NAME,GEOID,state_name,"Auto/Retail Debt Delinquency Rate, All","Auto/Retail Debt Delinquency Rate, Communities of Color","Auto/Retail Debt Delinquency Rate, Majority White Communities","Share of Subprime Consumers with Auto/Retail Delinquencies, All","Share of Near-Prime Consumers with Auto/Retail Delinquencies, All","Share of Prime Consumers with Auto/Retail Delinquencies, All","Share with Open Auto Debt, All","Share with Open Auto Debt, Communities of Color","Share with Open Auto Debt, Majority White Communities","Share with Open Auto/Retail Debt, All","Share with Open Auto/Retail Debt, Communities of Color","Share with Open Auto/Retail Debt, Majority White Communities","% population in rural areas, 2010 (Census)",poc_pct,"Average household income, 2019 (ACS)","Average non-white household income, 2019 (ACS)","Average white, non-Hispanic household income, 2019 (ACS)"
0,"Autauga County, Alabama",1001,Alabama,.0634218,n/a*,.0650155,.2628205,.0130719,0,.2623955,n/a*,.2649472,.3727019,n/a*,.3733881,0.420022,0.253973,75326,50809,82971
1,"Baldwin County, Alabama",1003,Alabama,.0428429,n/a**,.0427753,.2402464,.0205339,.0004912,.33154,n/a**,.3327853,.3993275,n/a**,.4010139,0.422791,0.169276,81449,47333,86522
2,"Barbour County, Alabama",1005,Alabama,.0868167,n/a*,n/a*,.297619,.015873,0,.2787958,.2435897,.3454545,.3979058,.2948718,.4181818,0.677896,0.541895,47068,31673,63382
3,"Bibb County, Alabama",1007,Alabama,.1048689,n/a**,.0917031,.3246753,n/a*,0,.3047619,n/a**,.3118081,.4111111,n/a**,.4095941,0.683526,0.254746,60182,40249,65273
4,"Blount County, Alabama",1009,Alabama,.0407876,n/a*,.0407876,.1746988,0,0,.2988116,n/a*,.2989807,.3978495,n/a*,.3980747,0.899515,0.131066,65639,49595,67146

In [9]:
debt_data_df.count()

NAME                                                                 3137
GEOID                                                                3137
state_name                                                           3137
Auto/Retail Debt Delinquency Rate, All                               3137
Auto/Retail Debt Delinquency Rate, Communities of Color              3137
Auto/Retail Debt Delinquency Rate, Majority White Communities        3137
Share of Subprime Consumers with Auto/Retail Delinquencies, All      3137
Share of Near-Prime Consumers with Auto/Retail Delinquencies, All    3137
Share of Prime Consumers with Auto/Retail Delinquencies, All         3137
Share with Open Auto Debt, All                                       3137
Share with Open Auto Debt, Communities of Color                      3137
Share with Open Auto Debt, Majority White Communities                3137
Share with Open Auto/Retail Debt, All                                3137
Share with Open Auto/Retail Debt, Communities of Color               3137
Share with Open Auto/Retail Debt, Majority White Communities         3137
% population in rural areas, 2010 (Census)                           3137
poc_pct                                                              3137
Average household income, 2019 (ACS)                                 3137
Average non-white household income, 2019 (ACS)                       3137
Average white, non-Hispanic household income, 2019 (ACS)             3137
dtype: int64

In [10]:
debt_data_df.dtypes

NAME                                                                  object
GEOID                                                                  int64
state_name                                                            object
Auto/Retail Debt Delinquency Rate, All                                object
Auto/Retail Debt Delinquency Rate, Communities of Color               object
Auto/Retail Debt Delinquency Rate, Majority White Communities         object
Share of Subprime Consumers with Auto/Retail Delinquencies, All       object
Share of Near-Prime Consumers with Auto/Retail Delinquencies, All     object
Share of Prime Consumers with Auto/Retail Delinquencies, All          object
Share with Open Auto Debt, All                                        object
Share with Open Auto Debt, Communities of Color                       object
Share with Open Auto Debt, Majority White Communities                 object
Share with Open Auto/Retail Debt, All                                 object
Share with Open Auto/Retail Debt, Communities of Color                object
Share with Open Auto/Retail Debt, Majority White Communities          object
% population in rural areas, 2010 (Census)                           float64
poc_pct                                                              float64
Average household income, 2019 (ACS)                                   int64
Average non-white household income, 2019 (ACS)                        object
Average white, non-Hispanic household income, 2019 (ACS)               int64
dtype: object

In [11]:
new_column_order= [
                         "state_name",
                         'NAME',
                         "Share with Open Auto Debt, All",
                         "Share with Open Auto Debt, Communities of Color",
                         "Share with Open Auto Debt, Majority White Communities",
                         "Average household income, 2019 (ACS)",
                         "Average non-white household income, 2019 (ACS)",
                         "Average white, non-Hispanic household income, 2019 (ACS)"]
debt_data_df=debt_data_df[new_column_order]
debt_data_df.head()

,state_name,NAME,"Share with Open Auto Debt, All","Share with Open Auto Debt, Communities of Color","Share with Open Auto Debt, Majority White Communities","Average household income, 2019 (ACS)","Average non-white household income, 2019 (ACS)","Average white, non-Hispanic household income, 2019 (ACS)"
0,Alabama,"Autauga County, Alabama",.2623955,n/a*,.2649472,75326,50809,82971
1,Alabama,"Baldwin County, Alabama",.33154,n/a**,.3327853,81449,47333,86522
2,Alabama,"Barbour County, Alabama",.2787958,.2435897,.3454545,47068,31673,63382
3,Alabama,"Bibb County, Alabama",.3047619,n/a**,.3118081,60182,40249,65273
4,Alabama,"Blount County, Alabama",.2988116,n/a*,.2989807,65639,49595,67146

In [12]:
len(debt_data_df)

3137

In [13]:
debt_data_df.isnull().count()

state_name                                                  3137
NAME                                                        3137
Share with Open Auto Debt, All                              3137
Share with Open Auto Debt, Communities of Color             3137
Share with Open Auto Debt, Majority White Communities       3137
Average household income, 2019 (ACS)                        3137
Average non-white household income, 2019 (ACS)              3137
Average white, non-Hispanic household income, 2019 (ACS)    3137
dtype: int64

In [14]:
debt_df = debt_data_df[['state_name', 'NAME','Share with Open Auto Debt, All', 'Share with Open Auto Debt, Communities of Color', 'Share with Open Auto Debt, Majority White Communities', 'Average household income, 2019 (ACS)', 'Average non-white household income, 2019 (ACS)', 'Average white, non-Hispanic household income, 2019 (ACS)']]
debt_df

,state_name,NAME,"Share with Open Auto Debt, All","Share with Open Auto Debt, Communities of Color","Share with Open Auto Debt, Majority White Communities","Average household income, 2019 (ACS)","Average non-white household income, 2019 (ACS)","Average white, non-Hispanic household income, 2019 (ACS)"
0,Alabama,"Autauga County, Alabama",.2623955,n/a*,.2649472,75326,50809,82971
1,Alabama,"Baldwin County, Alabama",.33154,n/a**,.3327853,81449,47333,86522
2,Alabama,"Barbour County, Alabama",.2787958,.2435897,.3454545,47068,31673,63382
3,Alabama,"Bibb County, Alabama",.3047619,n/a**,.3118081,60182,40249,65273
4,Alabama,"Blount County, Alabama",.2988116,n/a*,.2989807,65639,49595,67146
5,Alabama,"Bullock County, Alabama",.2777778,.2727273,n/a*,48571,39215,80344
6,Alabama,"Butler County, Alabama",.2351047,n/a*,.2786885,55971,40049,68198
7,Alabama,"Calhoun County, Alabama",.2871537,n/a**,.3079848,61137,39105,69780
8,Alabama,"Chambers County, Alabama",.2857143,n/a*,.3154472,53505,45986,59318
9,Alabama,"Cherokee County, Alabama",.3003755,n/a**,.3003755,57617,43107,58700
10,Alabama,"Chilton County, Alabama",.2815014,n/a*,.280027,62784,47591,65857
11,Alabama,"Choctaw County, Alabama",.2865014,.287037,.2744186,52395,36665,64098
12,Alabama,"Clarke County, Alabama",.3132023,n/a*,.2978723,54687,39235,66439
13,Alabama,"Clay County, Alabama",.2653061,n/a**,.2671569,57585,41044,61198
14,Alabama,"Cleburne County, Alabama",.3225108,n/a**,.323913,57990,48760,58698
15,Alabama,"Coffee County, Alabama",.3472222,n/a**,.351634,70079,52097,76975
16,Alabama,"Colbert County, Alabama",.2895472,n/a**,.2890272,60904,42998,65431
17,Alabama,"Conecuh County, Alabama",.3046358,.3030303,.3,47286,40122,54421
18,Alabama,"Coosa County, Alabama",.2738853,n/a*,.2844037,56017,37476,63947
19,Alabama,"Covington County, Alabama",.3012876,n/a*,.3019031,57075,35150,60794
20,Alabama,"Crenshaw County, Alabama",.3108911,n/a**,.3149284,61468,47966,66682
21,Alabama,"Cullman County, Alabama",.3008757,n/a**,.3031482,61920,50907,62594
22,Alabama,"Dale County, Alabama",.3198353,n/a**,.3215046,61001,48648,65921
23,Alabama,"Dallas County, Alabama",.2764004,.2769231,n/a*,47753,39144,67738
24,Alabama,"DeKalb County, Alabama",.2596339,n/a**,.2596339,56777,36970,59359
25,Alabama,"Elmore County, Alabama",.3015637,n/a**,.3018497,82576,61579,89085
26,Alabama,"Escambia County, Alabama",.3189509,n/a**,.2624114,50242,37092,57937
27,Alabama,"Etowah County, Alabama",.281717,n/a**,.2773973,59944,41337,64318
28,Alabama,"Fayette County, Alabama",.2577519,n/a**,.2577519,53897,32000,57335
29,Alabama,"Franklin County, Alabama",.3102679,n/a**,.3158784,56907,49122,58400
...,...,...,...,...,...,...,...,...
3107,Wisconsin,"Washburn County, Wisconsin",.3316832,n/a**,.3316832,64961,52204,65492
3108,Wisconsin,"Washington County, Wisconsin",.3340894,n/a**,.3340145,94877,73422,96050
3109,Wisconsin,"Waukesha County, Wisconsin",.3081181,n/a**,.3080009,119042,122610,118698
3110,Wisconsin,"Waupaca County, Wisconsin",.3704994,n/a**,.37078,73105,54100,73777
3111,Wisconsin,"Waushara County, Wisconsin",.3162055,n/a**,.3166227,68310,56058,68977
3112,Wisconsin,"Winnebago County, Wisconsin",.313055,n/a**,.3137106,77165,59698,78972
3113,Wisconsin,"Wood County, Wisconsin",.2687574,n/a**,.2687574,73613,54289,74572
3114,Wyoming,"Albany County, Wyoming",.3012704,n/a**,.3018182,68577,50818,71760
3115,Wyoming,"Big Horn County, Wyoming",.3008596,n/a**,.3008596,63375,47273,64729
3116,Wyoming,"Campbell County, Wyoming",.3991292,n/a**,.3986175,91699,63894,94362
3117,Wyoming,"Carbon County, Wyoming",.4013762,n/a**,.4013762,71697,64533,73317
3118,Wyoming,"Converse County, Wyoming",.3949192,n/a**,.3949192,81708,64023,83229
3119,Wyoming,"Crook County, Wyoming",.3971963,n/a**,.3971963,74378,86599,73981
3120,Wyoming,"Fremont County, Wyoming",.3044575,.2990654,.3095014,73599,59032,77165
3121,Wyoming,"Goshen County, Wyoming",.3089431,n/a**,.3097826,68090,62115,68838
3122,Wyoming,"Hot Springs County, Wyoming",.2435897,n/a**,.2435897,66157,80898,65097
3123,Wyoming,"Johnson County, Wyoming",.2284644,n/a**,.2284644,81359,49491,83862
3124,Wyoming,"Laramie County, Wyoming",.3698672,n/a**,.3736892,95612,90063,96546
3125,Wyoming,"Lincoln County, Wyoming",.3861066,n/a**,.3861066,80323,52076,81876
3126,Wyoming,"Natrona County, Wyoming",.3452523,n/a**,.3465468,79046,59436,81193
3127,Wyoming,"Niobrara County, Wyoming",.3125,n/a**,.3125,54980,114536,54293
3128,Wyoming,"Park County, Wyoming",.2744887,n/a**,.2744887,82323,44783,84620
3129,Wyoming,"Platte County, Wyoming",.2941177,n/a**,.2941177,77665,64066,79422
3130,Wyoming,"Sheridan County, Wyoming",.3065327,n/a**,.3065327,80525,60168,81885
3131,Wyoming,"Sublette County, Wyoming",.4052045,n/a**,.4052045,92755,91896,92811
3132,Wyoming,"Sweetwater County, Wyoming",.4200164,n/a**,.4255499,85346,64674,89540
3133,Wyoming,"Teton County, Wyoming",.2642424,n/a**,.2479609,132531,71564,141299
3134,Wyoming,"Uinta County, Wyoming",.4119658,n/a**,.4179894,74938,72010,75273
3135,Wyoming,"Washakie County, Wyoming",.2627451,n/a**,.2627451,65496,56047,67192
3136,Wyoming,"Weston County, Wyoming",.387931,n/a**,.3896104,68877,37509,69485

In [15]:
county_name_df= debt_df['NAME'].str.split(",",expand=True)
county_name_df

                       0           1
0         Autauga County     Alabama
1         Baldwin County     Alabama
2         Barbour County     Alabama
3            Bibb County     Alabama
4          Blount County     Alabama
5         Bullock County     Alabama
6          Butler County     Alabama
7         Calhoun County     Alabama
8        Chambers County     Alabama
9        Cherokee County     Alabama
10        Chilton County     Alabama
11        Choctaw County     Alabama
12         Clarke County     Alabama
13           Clay County     Alabama
14       Cleburne County     Alabama
15         Coffee County     Alabama
16        Colbert County     Alabama
17        Conecuh County     Alabama
18          Coosa County     Alabama
19      Covington County     Alabama
20       Crenshaw County     Alabama
21        Cullman County     Alabama
22           Dale County     Alabama
23         Dallas County     Alabama
24         DeKalb County     Alabama
25         Elmore County     Alabama
26       Escambia County     Alabama
27         Etowah County     Alabama
28        Fayette County     Alabama
29       Franklin County     Alabama
...                  ...         ...
3107     Washburn County   Wisconsin
3108   Washington County   Wisconsin
3109     Waukesha County   Wisconsin
3110      Waupaca County   Wisconsin
3111     Waushara County   Wisconsin
3112    Winnebago County   Wisconsin
3113         Wood County   Wisconsin
3114       Albany County     Wyoming
3115     Big Horn County     Wyoming
3116     Campbell County     Wyoming
3117       Carbon County     Wyoming
3118     Converse County     Wyoming
3119        Crook County     Wyoming
3120      Fremont County     Wyoming
3121       Goshen County     Wyoming
3122  Hot Springs County     Wyoming
3123      Johnson County     Wyoming
3124      Laramie County     Wyoming
3125      Lincoln County     Wyoming
3126      Natrona County     Wyoming
3127     Niobrara County     Wyoming
3128         Park County     Wyoming
3129       Platte County     Wyoming
3130     Sheridan County     Wyoming
3131     Sublette County     Wyoming
3132   Sweetwater County     Wyoming
3133        Teton County     Wyoming
3134        Uinta County     Wyoming
3135     Washakie County     Wyoming
3136       Weston County     Wyoming

[3137 rows x 2 columns]

In [16]:
debt_df['county_name'] = debt_df['NAME'].str.split(' ').str[0]
debt_df['county_name'] = debt_df['county_name'].str.upper()

In [17]:
debt_df.head()

,state_name,NAME,"Share with Open Auto Debt, All","Share with Open Auto Debt, Communities of Color","Share with Open Auto Debt, Majority White Communities","Average household income, 2019 (ACS)","Average non-white household income, 2019 (ACS)","Average white, non-Hispanic household income, 2019 (ACS)",county_name
0,Alabama,"Autauga County, Alabama",.2623955,n/a*,.2649472,75326,50809,82971,AUTAUGA
1,Alabama,"Baldwin County, Alabama",.33154,n/a**,.3327853,81449,47333,86522,BALDWIN
2,Alabama,"Barbour County, Alabama",.2787958,.2435897,.3454545,47068,31673,63382,BARBOUR
3,Alabama,"Bibb County, Alabama",.3047619,n/a**,.3118081,60182,40249,65273,BIBB
4,Alabama,"Blount County, Alabama",.2988116,n/a*,.2989807,65639,49595,67146,BLOUNT

In [18]:
new_column_order= [
                         "state_name",
                         "county_name",
                         "Share with Open Auto Debt, All",
                         "Share with Open Auto Debt, Communities of Color",
                         "Share with Open Auto Debt, Majority White Communities",
                         "Average household income, 2019 (ACS)",
                         "Average non-white household income, 2019 (ACS)",
                         "Average white, non-Hispanic household income, 2019 (ACS)"]
debt_df=debt_df[new_column_order]
debt_df

,state_name,county_name,"Share with Open Auto Debt, All","Share with Open Auto Debt, Communities of Color","Share with Open Auto Debt, Majority White Communities","Average household income, 2019 (ACS)","Average non-white household income, 2019 (ACS)","Average white, non-Hispanic household income, 2019 (ACS)"
0,Alabama,AUTAUGA,.2623955,n/a*,.2649472,75326,50809,82971
1,Alabama,BALDWIN,.33154,n/a**,.3327853,81449,47333,86522
2,Alabama,BARBOUR,.2787958,.2435897,.3454545,47068,31673,63382
3,Alabama,BIBB,.3047619,n/a**,.3118081,60182,40249,65273
4,Alabama,BLOUNT,.2988116,n/a*,.2989807,65639,49595,67146
5,Alabama,BULLOCK,.2777778,.2727273,n/a*,48571,39215,80344
6,Alabama,BUTLER,.2351047,n/a*,.2786885,55971,40049,68198
7,Alabama,CALHOUN,.2871537,n/a**,.3079848,61137,39105,69780
8,Alabama,CHAMBERS,.2857143,n/a*,.3154472,53505,45986,59318
9,Alabama,CHEROKEE,.3003755,n/a**,.3003755,57617,43107,58700
10,Alabama,CHILTON,.2815014,n/a*,.280027,62784,47591,65857
11,Alabama,CHOCTAW,.2865014,.287037,.2744186,52395,36665,64098
12,Alabama,CLARKE,.3132023,n/a*,.2978723,54687,39235,66439
13,Alabama,CLAY,.2653061,n/a**,.2671569,57585,41044,61198
14,Alabama,CLEBURNE,.3225108,n/a**,.323913,57990,48760,58698
15,Alabama,COFFEE,.3472222,n/a**,.351634,70079,52097,76975
16,Alabama,COLBERT,.2895472,n/a**,.2890272,60904,42998,65431
17,Alabama,CONECUH,.3046358,.3030303,.3,47286,40122,54421
18,Alabama,COOSA,.2738853,n/a*,.2844037,56017,37476,63947
19,Alabama,COVINGTON,.3012876,n/a*,.3019031,57075,35150,60794
20,Alabama,CRENSHAW,.3108911,n/a**,.3149284,61468,47966,66682
21,Alabama,CULLMAN,.3008757,n/a**,.3031482,61920,50907,62594
22,Alabama,DALE,.3198353,n/a**,.3215046,61001,48648,65921
23,Alabama,DALLAS,.2764004,.2769231,n/a*,47753,39144,67738
24,Alabama,DEKALB,.2596339,n/a**,.2596339,56777,36970,59359
25,Alabama,ELMORE,.3015637,n/a**,.3018497,82576,61579,89085
26,Alabama,ESCAMBIA,.3189509,n/a**,.2624114,50242,37092,57937
27,Alabama,ETOWAH,.281717,n/a**,.2773973,59944,41337,64318
28,Alabama,FAYETTE,.2577519,n/a**,.2577519,53897,32000,57335
29,Alabama,FRANKLIN,.3102679,n/a**,.3158784,56907,49122,58400
...,...,...,...,...,...,...,...,...
3107,Wisconsin,WASHBURN,.3316832,n/a**,.3316832,64961,52204,65492
3108,Wisconsin,WASHINGTON,.3340894,n/a**,.3340145,94877,73422,96050
3109,Wisconsin,WAUKESHA,.3081181,n/a**,.3080009,119042,122610,118698
3110,Wisconsin,WAUPACA,.3704994,n/a**,.37078,73105,54100,73777
3111,Wisconsin,WAUSHARA,.3162055,n/a**,.3166227,68310,56058,68977
3112,Wisconsin,WINNEBAGO,.313055,n/a**,.3137106,77165,59698,78972
3113,Wisconsin,WOOD,.2687574,n/a**,.2687574,73613,54289,74572
3114,Wyoming,ALBANY,.3012704,n/a**,.3018182,68577,50818,71760
3115,Wyoming,BIG,.3008596,n/a**,.3008596,63375,47273,64729
3116,Wyoming,CAMPBELL,.3991292,n/a**,.3986175,91699,63894,94362
3117,Wyoming,CARBON,.4013762,n/a**,.4013762,71697,64533,73317
3118,Wyoming,CONVERSE,.3949192,n/a**,.3949192,81708,64023,83229
3119,Wyoming,CROOK,.3971963,n/a**,.3971963,74378,86599,73981
3120,Wyoming,FREMONT,.3044575,.2990654,.3095014,73599,59032,77165
3121,Wyoming,GOSHEN,.3089431,n/a**,.3097826,68090,62115,68838
3122,Wyoming,HOT,.2435897,n/a**,.2435897,66157,80898,65097
3123,Wyoming,JOHNSON,.2284644,n/a**,.2284644,81359,49491,83862
3124,Wyoming,LARAMIE,.3698672,n/a**,.3736892,95612,90063,96546
3125,Wyoming,LINCOLN,.3861066,n/a**,.3861066,80323,52076,81876
3126,Wyoming,NATRONA,.3452523,n/a**,.3465468,79046,59436,81193
3127,Wyoming,NIOBRARA,.3125,n/a**,.3125,54980,114536,54293
3128,Wyoming,PARK,.2744887,n/a**,.2744887,82323,44783,84620
3129,Wyoming,PLATTE,.2941177,n/a**,.2941177,77665,64066,79422
3130,Wyoming,SHERIDAN,.3065327,n/a**,.3065327,80525,60168,81885
3131,Wyoming,SUBLETTE,.4052045,n/a**,.4052045,92755,91896,92811
3132,Wyoming,SWEETWATER,.4200164,n/a**,.4255499,85346,64674,89540
3133,Wyoming,TETON,.2642424,n/a**,.2479609,132531,71564,141299
3134,Wyoming,UINTA,.4119658,n/a**,.4179894,74938,72010,75273
3135,Wyoming,WASHAKIE,.2627451,n/a**,.2627451,65496,56047,67192
3136,Wyoming,WESTON,.387931,n/a**,.3896104,68877,37509,69485

In [19]:
debt_df.rename({"Share with Open Auto Debt, All": "Debt_All",
                         "Share with Open Auto Debt, Communities of Color": "Debt_Communities_Color",
                         "Share with Open Auto Debt, Majority White Communities": "Debt_Majorities_White",
                         "Average household income, 2019 (ACS)":"Avg_Household_Income_All",
                         "Average non-white household income, 2019 (ACS)": "Avg_Non_White_Income",
                         "Average white, non-Hispanic household income, 2019 (ACS)":  "Avg_Non_Hispanic"
                       }, axis=1, inplace=True)
debt_df

C:\Users\alelo\anaconda3\envs\PythonData\lib\site-packages\pandas\core\frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

,state_name,county_name,Debt_All,Debt_Communities_Color,Debt_Majorities_White,Avg_Household_Income_All,Avg_Non_White_Income,Avg_Non_Hispanic
0,Alabama,AUTAUGA,.2623955,n/a*,.2649472,75326,50809,82971
1,Alabama,BALDWIN,.33154,n/a**,.3327853,81449,47333,86522
2,Alabama,BARBOUR,.2787958,.2435897,.3454545,47068,31673,63382
3,Alabama,BIBB,.3047619,n/a**,.3118081,60182,40249,65273
4,Alabama,BLOUNT,.2988116,n/a*,.2989807,65639,49595,67146
5,Alabama,BULLOCK,.2777778,.2727273,n/a*,48571,39215,80344
6,Alabama,BUTLER,.2351047,n/a*,.2786885,55971,40049,68198
7,Alabama,CALHOUN,.2871537,n/a**,.3079848,61137,39105,69780
8,Alabama,CHAMBERS,.2857143,n/a*,.3154472,53505,45986,59318
9,Alabama,CHEROKEE,.3003755,n/a**,.3003755,57617,43107,58700
10,Alabama,CHILTON,.2815014,n/a*,.280027,62784,47591,65857
11,Alabama,CHOCTAW,.2865014,.287037,.2744186,52395,36665,64098
12,Alabama,CLARKE,.3132023,n/a*,.2978723,54687,39235,66439
13,Alabama,CLAY,.2653061,n/a**,.2671569,57585,41044,61198
14,Alabama,CLEBURNE,.3225108,n/a**,.323913,57990,48760,58698
15,Alabama,COFFEE,.3472222,n/a**,.351634,70079,52097,76975
16,Alabama,COLBERT,.2895472,n/a**,.2890272,60904,42998,65431
17,Alabama,CONECUH,.3046358,.3030303,.3,47286,40122,54421
18,Alabama,COOSA,.2738853,n/a*,.2844037,56017,37476,63947
19,Alabama,COVINGTON,.3012876,n/a*,.3019031,57075,35150,60794
20,Alabama,CRENSHAW,.3108911,n/a**,.3149284,61468,47966,66682
21,Alabama,CULLMAN,.3008757,n/a**,.3031482,61920,50907,62594
22,Alabama,DALE,.3198353,n/a**,.3215046,61001,48648,65921
23,Alabama,DALLAS,.2764004,.2769231,n/a*,47753,39144,67738
24,Alabama,DEKALB,.2596339,n/a**,.2596339,56777,36970,59359
25,Alabama,ELMORE,.3015637,n/a**,.3018497,82576,61579,89085
26,Alabama,ESCAMBIA,.3189509,n/a**,.2624114,50242,37092,57937
27,Alabama,ETOWAH,.281717,n/a**,.2773973,59944,41337,64318
28,Alabama,FAYETTE,.2577519,n/a**,.2577519,53897,32000,57335
29,Alabama,FRANKLIN,.3102679,n/a**,.3158784,56907,49122,58400
...,...,...,...,...,...,...,...,...
3107,Wisconsin,WASHBURN,.3316832,n/a**,.3316832,64961,52204,65492
3108,Wisconsin,WASHINGTON,.3340894,n/a**,.3340145,94877,73422,96050
3109,Wisconsin,WAUKESHA,.3081181,n/a**,.3080009,119042,122610,118698
3110,Wisconsin,WAUPACA,.3704994,n/a**,.37078,73105,54100,73777
3111,Wisconsin,WAUSHARA,.3162055,n/a**,.3166227,68310,56058,68977
3112,Wisconsin,WINNEBAGO,.313055,n/a**,.3137106,77165,59698,78972
3113,Wisconsin,WOOD,.2687574,n/a**,.2687574,73613,54289,74572
3114,Wyoming,ALBANY,.3012704,n/a**,.3018182,68577,50818,71760
3115,Wyoming,BIG,.3008596,n/a**,.3008596,63375,47273,64729
3116,Wyoming,CAMPBELL,.3991292,n/a**,.3986175,91699,63894,94362
3117,Wyoming,CARBON,.4013762,n/a**,.4013762,71697,64533,73317
3118,Wyoming,CONVERSE,.3949192,n/a**,.3949192,81708,64023,83229
3119,Wyoming,CROOK,.3971963,n/a**,.3971963,74378,86599,73981
3120,Wyoming,FREMONT,.3044575,.2990654,.3095014,73599,59032,77165
3121,Wyoming,GOSHEN,.3089431,n/a**,.3097826,68090,62115,68838
3122,Wyoming,HOT,.2435897,n/a**,.2435897,66157,80898,65097
3123,Wyoming,JOHNSON,.2284644,n/a**,.2284644,81359,49491,83862
3124,Wyoming,LARAMIE,.3698672,n/a**,.3736892,95612,90063,96546
3125,Wyoming,LINCOLN,.3861066,n/a**,.3861066,80323,52076,81876
3126,Wyoming,NATRONA,.3452523,n/a**,.3465468,79046,59436,81193
3127,Wyoming,NIOBRARA,.3125,n/a**,.3125,54980,114536,54293
3128,Wyoming,PARK,.2744887,n/a**,.2744887,82323,44783,84620
3129,Wyoming,PLATTE,.2941177,n/a**,.2941177,77665,64066,79422
3130,Wyoming,SHERIDAN,.3065327,n/a**,.3065327,80525,60168,81885
3131,Wyoming,SUBLETTE,.4052045,n/a**,.4052045,92755,91896,92811
3132,Wyoming,SWEETWATER,.4200164,n/a**,.4255499,85346,64674,89540
3133,Wyoming,TETON,.2642424,n/a**,.2479609,132531,71564,141299
3134,Wyoming,UINTA,.4119658,n/a**,.4179894,74938,72010,75273
3135,Wyoming,WASHAKIE,.2627451,n/a**,.2627451,65496,56047,67192
3136,Wyoming,WESTON,.387931,n/a**,.3896104,68877,37509,69485

In [20]:
debt_clean_df1=debt_df.replace(['n/a*'], 49)
debt_clean_df1

,state_name,county_name,Debt_All,Debt_Communities_Color,Debt_Majorities_White,Avg_Household_Income_All,Avg_Non_White_Income,Avg_Non_Hispanic
0,Alabama,AUTAUGA,.2623955,49,.2649472,75326,50809,82971
1,Alabama,BALDWIN,.33154,n/a**,.3327853,81449,47333,86522
2,Alabama,BARBOUR,.2787958,.2435897,.3454545,47068,31673,63382
3,Alabama,BIBB,.3047619,n/a**,.3118081,60182,40249,65273
4,Alabama,BLOUNT,.2988116,49,.2989807,65639,49595,67146
5,Alabama,BULLOCK,.2777778,.2727273,49,48571,39215,80344
6,Alabama,BUTLER,.2351047,49,.2786885,55971,40049,68198
7,Alabama,CALHOUN,.2871537,n/a**,.3079848,61137,39105,69780
8,Alabama,CHAMBERS,.2857143,49,.3154472,53505,45986,59318
9,Alabama,CHEROKEE,.3003755,n/a**,.3003755,57617,43107,58700
10,Alabama,CHILTON,.2815014,49,.280027,62784,47591,65857
11,Alabama,CHOCTAW,.2865014,.287037,.2744186,52395,36665,64098
12,Alabama,CLARKE,.3132023,49,.2978723,54687,39235,66439
13,Alabama,CLAY,.2653061,n/a**,.2671569,57585,41044,61198
14,Alabama,CLEBURNE,.3225108,n/a**,.323913,57990,48760,58698
15,Alabama,COFFEE,.3472222,n/a**,.351634,70079,52097,76975
16,Alabama,COLBERT,.2895472,n/a**,.2890272,60904,42998,65431
17,Alabama,CONECUH,.3046358,.3030303,.3,47286,40122,54421
18,Alabama,COOSA,.2738853,49,.2844037,56017,37476,63947
19,Alabama,COVINGTON,.3012876,49,.3019031,57075,35150,60794
20,Alabama,CRENSHAW,.3108911,n/a**,.3149284,61468,47966,66682
21,Alabama,CULLMAN,.3008757,n/a**,.3031482,61920,50907,62594
22,Alabama,DALE,.3198353,n/a**,.3215046,61001,48648,65921
23,Alabama,DALLAS,.2764004,.2769231,49,47753,39144,67738
24,Alabama,DEKALB,.2596339,n/a**,.2596339,56777,36970,59359
25,Alabama,ELMORE,.3015637,n/a**,.3018497,82576,61579,89085
26,Alabama,ESCAMBIA,.3189509,n/a**,.2624114,50242,37092,57937
27,Alabama,ETOWAH,.281717,n/a**,.2773973,59944,41337,64318
28,Alabama,FAYETTE,.2577519,n/a**,.2577519,53897,32000,57335
29,Alabama,FRANKLIN,.3102679,n/a**,.3158784,56907,49122,58400
...,...,...,...,...,...,...,...,...
3107,Wisconsin,WASHBURN,.3316832,n/a**,.3316832,64961,52204,65492
3108,Wisconsin,WASHINGTON,.3340894,n/a**,.3340145,94877,73422,96050
3109,Wisconsin,WAUKESHA,.3081181,n/a**,.3080009,119042,122610,118698
3110,Wisconsin,WAUPACA,.3704994,n/a**,.37078,73105,54100,73777
3111,Wisconsin,WAUSHARA,.3162055,n/a**,.3166227,68310,56058,68977
3112,Wisconsin,WINNEBAGO,.313055,n/a**,.3137106,77165,59698,78972
3113,Wisconsin,WOOD,.2687574,n/a**,.2687574,73613,54289,74572
3114,Wyoming,ALBANY,.3012704,n/a**,.3018182,68577,50818,71760
3115,Wyoming,BIG,.3008596,n/a**,.3008596,63375,47273,64729
3116,Wyoming,CAMPBELL,.3991292,n/a**,.3986175,91699,63894,94362
3117,Wyoming,CARBON,.4013762,n/a**,.4013762,71697,64533,73317
3118,Wyoming,CONVERSE,.3949192,n/a**,.3949192,81708,64023,83229
3119,Wyoming,CROOK,.3971963,n/a**,.3971963,74378,86599,73981
3120,Wyoming,FREMONT,.3044575,.2990654,.3095014,73599,59032,77165
3121,Wyoming,GOSHEN,.3089431,n/a**,.3097826,68090,62115,68838
3122,Wyoming,HOT,.2435897,n/a**,.2435897,66157,80898,65097
3123,Wyoming,JOHNSON,.2284644,n/a**,.2284644,81359,49491,83862
3124,Wyoming,LARAMIE,.3698672,n/a**,.3736892,95612,90063,96546
3125,Wyoming,LINCOLN,.3861066,n/a**,.3861066,80323,52076,81876
3126,Wyoming,NATRONA,.3452523,n/a**,.3465468,79046,59436,81193
3127,Wyoming,NIOBRARA,.3125,n/a**,.3125,54980,114536,54293
3128,Wyoming,PARK,.2744887,n/a**,.2744887,82323,44783,84620
3129,Wyoming,PLATTE,.2941177,n/a**,.2941177,77665,64066,79422
3130,Wyoming,SHERIDAN,.3065327,n/a**,.3065327,80525,60168,81885
3131,Wyoming,SUBLETTE,.4052045,n/a**,.4052045,92755,91896,92811
3132,Wyoming,SWEETWATER,.4200164,n/a**,.4255499,85346,64674,89540
3133,Wyoming,TETON,.2642424,n/a**,.2479609,132531,71564,141299
3134,Wyoming,UINTA,.4119658,n/a**,.4179894,74938,72010,75273
3135,Wyoming,WASHAKIE,.2627451,n/a**,.2627451,65496,56047,67192
3136,Wyoming,WESTON,.387931,n/a**,.3896104,68877,37509,69485

In [21]:
debt_clean_df=debt_clean_df1.replace(['n/a**'], 49)
debt_clean_df

,state_name,county_name,Debt_All,Debt_Communities_Color,Debt_Majorities_White,Avg_Household_Income_All,Avg_Non_White_Income,Avg_Non_Hispanic
0,Alabama,AUTAUGA,.2623955,49,.2649472,75326,50809,82971
1,Alabama,BALDWIN,.33154,49,.3327853,81449,47333,86522
2,Alabama,BARBOUR,.2787958,.2435897,.3454545,47068,31673,63382
3,Alabama,BIBB,.3047619,49,.3118081,60182,40249,65273
4,Alabama,BLOUNT,.2988116,49,.2989807,65639,49595,67146
5,Alabama,BULLOCK,.2777778,.2727273,49,48571,39215,80344
6,Alabama,BUTLER,.2351047,49,.2786885,55971,40049,68198
7,Alabama,CALHOUN,.2871537,49,.3079848,61137,39105,69780
8,Alabama,CHAMBERS,.2857143,49,.3154472,53505,45986,59318
9,Alabama,CHEROKEE,.3003755,49,.3003755,57617,43107,58700
10,Alabama,CHILTON,.2815014,49,.280027,62784,47591,65857
11,Alabama,CHOCTAW,.2865014,.287037,.2744186,52395,36665,64098
12,Alabama,CLARKE,.3132023,49,.2978723,54687,39235,66439
13,Alabama,CLAY,.2653061,49,.2671569,57585,41044,61198
14,Alabama,CLEBURNE,.3225108,49,.323913,57990,48760,58698
15,Alabama,COFFEE,.3472222,49,.351634,70079,52097,76975
16,Alabama,COLBERT,.2895472,49,.2890272,60904,42998,65431
17,Alabama,CONECUH,.3046358,.3030303,.3,47286,40122,54421
18,Alabama,COOSA,.2738853,49,.2844037,56017,37476,63947
19,Alabama,COVINGTON,.3012876,49,.3019031,57075,35150,60794
20,Alabama,CRENSHAW,.3108911,49,.3149284,61468,47966,66682
21,Alabama,CULLMAN,.3008757,49,.3031482,61920,50907,62594
22,Alabama,DALE,.3198353,49,.3215046,61001,48648,65921
23,Alabama,DALLAS,.2764004,.2769231,49,47753,39144,67738
24,Alabama,DEKALB,.2596339,49,.2596339,56777,36970,59359
25,Alabama,ELMORE,.3015637,49,.3018497,82576,61579,89085
26,Alabama,ESCAMBIA,.3189509,49,.2624114,50242,37092,57937
27,Alabama,ETOWAH,.281717,49,.2773973,59944,41337,64318
28,Alabama,FAYETTE,.2577519,49,.2577519,53897,32000,57335
29,Alabama,FRANKLIN,.3102679,49,.3158784,56907,49122,58400
...,...,...,...,...,...,...,...,...
3107,Wisconsin,WASHBURN,.3316832,49,.3316832,64961,52204,65492
3108,Wisconsin,WASHINGTON,.3340894,49,.3340145,94877,73422,96050
3109,Wisconsin,WAUKESHA,.3081181,49,.3080009,119042,122610,118698
3110,Wisconsin,WAUPACA,.3704994,49,.37078,73105,54100,73777
3111,Wisconsin,WAUSHARA,.3162055,49,.3166227,68310,56058,68977
3112,Wisconsin,WINNEBAGO,.313055,49,.3137106,77165,59698,78972
3113,Wisconsin,WOOD,.2687574,49,.2687574,73613,54289,74572
3114,Wyoming,ALBANY,.3012704,49,.3018182,68577,50818,71760
3115,Wyoming,BIG,.3008596,49,.3008596,63375,47273,64729
3116,Wyoming,CAMPBELL,.3991292,49,.3986175,91699,63894,94362
3117,Wyoming,CARBON,.4013762,49,.4013762,71697,64533,73317
3118,Wyoming,CONVERSE,.3949192,49,.3949192,81708,64023,83229
3119,Wyoming,CROOK,.3971963,49,.3971963,74378,86599,73981
3120,Wyoming,FREMONT,.3044575,.2990654,.3095014,73599,59032,77165
3121,Wyoming,GOSHEN,.3089431,49,.3097826,68090,62115,68838
3122,Wyoming,HOT,.2435897,49,.2435897,66157,80898,65097
3123,Wyoming,JOHNSON,.2284644,49,.2284644,81359,49491,83862
3124,Wyoming,LARAMIE,.3698672,49,.3736892,95612,90063,96546
3125,Wyoming,LINCOLN,.3861066,49,.3861066,80323,52076,81876
3126,Wyoming,NATRONA,.3452523,49,.3465468,79046,59436,81193
3127,Wyoming,NIOBRARA,.3125,49,.3125,54980,114536,54293
3128,Wyoming,PARK,.2744887,49,.2744887,82323,44783,84620
3129,Wyoming,PLATTE,.2941177,49,.2941177,77665,64066,79422
3130,Wyoming,SHERIDAN,.3065327,49,.3065327,80525,60168,81885
3131,Wyoming,SUBLETTE,.4052045,49,.4052045,92755,91896,92811
3132,Wyoming,SWEETWATER,.4200164,49,.4255499,85346,64674,89540
3133,Wyoming,TETON,.2642424,49,.2479609,132531,71564,141299
3134,Wyoming,UINTA,.4119658,49,.4179894,74938,72010,75273
3135,Wyoming,WASHAKIE,.2627451,49,.2627451,65496,56047,67192
3136,Wyoming,WESTON,.387931,49,.3896104,68877,37509,69485

In [22]:
debt_clean_df3= debt_clean_df.drop_duplicates(subset= 'county_name', keep='last')

In [23]:
debt_clean_df3[debt_clean_df3['county_name']== 'ALEUTIANS']

,state_name,county_name,Debt_All,Debt_Communities_Color,Debt_Majorities_White,Avg_Household_Income_All,Avg_Non_White_Income,Avg_Non_Hispanic
68,Alaska,ALEUTIANS,.1038961,.1038961,49,101964,86979,133787

In [24]:
debt_clean_df3

,state_name,county_name,Debt_All,Debt_Communities_Color,Debt_Majorities_White,Avg_Household_Income_All,Avg_Non_White_Income,Avg_Non_Hispanic
0,Alabama,AUTAUGA,.2623955,49,.2649472,75326,50809,82971
5,Alabama,BULLOCK,.2777778,.2727273,49,48571,39215,80344
10,Alabama,CHILTON,.2815014,49,.280027,62784,47591,65857
16,Alabama,COLBERT,.2895472,49,.2890272,60904,42998,65431
17,Alabama,CONECUH,.3046358,.3030303,.3,47286,40122,54421
18,Alabama,COOSA,.2738853,49,.2844037,56017,37476,63947
20,Alabama,CRENSHAW,.3108911,49,.3149284,61468,47966,66682
21,Alabama,CULLMAN,.3008757,49,.3031482,61920,50907,62594
22,Alabama,DALE,.3198353,49,.3215046,61001,48648,65921
27,Alabama,ETOWAH,.281717,49,.2773973,59944,41337,64318
30,Alabama,GENEVA,.3071749,49,.3075196,53077,38198,55244
45,Alabama,MARENGO,.3255426,.3473684,.245283,54556,42686,70338
48,Alabama,MOBILE,.2901475,.2586858,.3098539,64556,47658,76669
60,Alabama,TALLADEGA,.2459872,49,.2464945,62758,52332,68492
61,Alabama,TALLAPOOSA,.247605,.3294118,.2442053,60734,39221,68552
62,Alabama,TUSCALOOSA,.3090464,49,.3309971,73432,52839,84986
68,Alaska,ALEUTIANS,.1038961,.1038961,49,101964,86979,133787
69,Alaska,ANCHORAGE,.3041687,.2756696,.3036756,109042,86133,121674
70,Alaska,BETHEL,.1205674,.1205674,49,70804,59999,132395
72,Alaska,DENALI,.2941177,49,.2941177,85694,73123,87109
73,Alaska,DILLINGHAM,.1782178,.1782178,49,72576,65900,114253
74,Alaska,FAIRBANKS,.3503909,49,.356021,103334,109301,101587
75,Alaska,HAINES,.1232877,49,.1232877,72356,46093,77207
77,Alaska,KENAI,.2640092,49,.2667457,85348,71327,87619
78,Alaska,KETCHIKAN,.2137931,49,.2155388,92764,75027,100439
79,Alaska,KODIAK,.2886905,49,49,94946,82439,103039
80,Alaska,KUSILVAK,.0409836,.0409836,49,47654,46211,105445
82,Alaska,MATANUSKA-SUSITNA,.3301435,49,.3198068,92126,75535,95478
83,Alaska,NOME,.1609195,.1609195,49,76581,64278,124191
84,Alaska,NORTH,.2820513,.283871,49,94169,88352,147085
...,...,...,...,...,...,...,...,...
3107,Wisconsin,WASHBURN,.3316832,49,.3316832,64961,52204,65492
3108,Wisconsin,WASHINGTON,.3340894,49,.3340145,94877,73422,96050
3109,Wisconsin,WAUKESHA,.3081181,49,.3080009,119042,122610,118698
3110,Wisconsin,WAUPACA,.3704994,49,.37078,73105,54100,73777
3111,Wisconsin,WAUSHARA,.3162055,49,.3166227,68310,56058,68977
3112,Wisconsin,WINNEBAGO,.313055,49,.3137106,77165,59698,78972
3113,Wisconsin,WOOD,.2687574,49,.2687574,73613,54289,74572
3114,Wyoming,ALBANY,.3012704,49,.3018182,68577,50818,71760
3115,Wyoming,BIG,.3008596,49,.3008596,63375,47273,64729
3116,Wyoming,CAMPBELL,.3991292,49,.3986175,91699,63894,94362
3117,Wyoming,CARBON,.4013762,49,.4013762,71697,64533,73317
3118,Wyoming,CONVERSE,.3949192,49,.3949192,81708,64023,83229
3119,Wyoming,CROOK,.3971963,49,.3971963,74378,86599,73981
3120,Wyoming,FREMONT,.3044575,.2990654,.3095014,73599,59032,77165
3121,Wyoming,GOSHEN,.3089431,49,.3097826,68090,62115,68838
3122,Wyoming,HOT,.2435897,49,.2435897,66157,80898,65097
3123,Wyoming,JOHNSON,.2284644,49,.2284644,81359,49491,83862
3124,Wyoming,LARAMIE,.3698672,49,.3736892,95612,90063,96546
3125,Wyoming,LINCOLN,.3861066,49,.3861066,80323,52076,81876
3126,Wyoming,NATRONA,.3452523,49,.3465468,79046,59436,81193
3127,Wyoming,NIOBRARA,.3125,49,.3125,54980,114536,54293
3128,Wyoming,PARK,.2744887,49,.2744887,82323,44783,84620
3129,Wyoming,PLATTE,.2941177,49,.2941177,77665,64066,79422
3130,Wyoming,SHERIDAN,.3065327,49,.3065327,80525,60168,81885
3131,Wyoming,SUBLETTE,.4052045,49,.4052045,92755,91896,92811
3132,Wyoming,SWEETWATER,.4200164,49,.4255499,85346,64674,89540
3133,Wyoming,TETON,.2642424,49,.2479609,132531,71564,141299
3134,Wyoming,UINTA,.4119658,49,.4179894,74938,72010,75273
3135,Wyoming,WASHAKIE,.2627451,49,.2627451,65496,56047,67192
3136,Wyoming,WESTON,.387931,49,.3896104,68877,37509,69485

In [25]:
debt_clean_df3.to_csv("debt_clean_vf.csv", index=False)

In [26]:
debt_clean_df3.to_sql('debt_clean_vf', con = engine, index=False, if_exists = 'replace')

# COUNTY VOTES DATABASE

In [27]:
county_elections_df = pd.read_csv(county_elections_to_load)
county_elections_df.head()

,year,state,state_po,county_name,county_fips,office,candidate,party,candidatevotes,totalvotes,version,mode
0,2000,ALABAMA,AL,AUTAUGA,1001.0,US PRESIDENT,AL GORE,DEMOCRAT,4942,17208,20220315,TOTAL
1,2000,ALABAMA,AL,AUTAUGA,1001.0,US PRESIDENT,GEORGE W. BUSH,REPUBLICAN,11993,17208,20220315,TOTAL
2,2000,ALABAMA,AL,AUTAUGA,1001.0,US PRESIDENT,RALPH NADER,GREEN,160,17208,20220315,TOTAL
3,2000,ALABAMA,AL,AUTAUGA,1001.0,US PRESIDENT,OTHER,OTHER,113,17208,20220315,TOTAL
4,2000,ALABAMA,AL,BALDWIN,1003.0,US PRESIDENT,AL GORE,DEMOCRAT,13997,56480,20220315,TOTAL

In [28]:
county_elections_df.count()

year              72617
state             72617
state_po          72617
county_name       72617
county_fips       72560
office            72617
candidate         72617
party             72617
candidatevotes    72617
totalvotes        72617
version           72617
mode              72617
dtype: int64

In [29]:
county_elections_df.isnull().count()

year              72617
state             72617
state_po          72617
county_name       72617
county_fips       72617
office            72617
candidate         72617
party             72617
candidatevotes    72617
totalvotes        72617
version           72617
mode              72617
dtype: int64

In [30]:
county_elections_df.dtypes

year                int64
state              object
state_po           object
county_name        object
county_fips       float64
office             object
candidate          object
party              object
candidatevotes      int64
totalvotes          int64
version             int64
mode               object
dtype: object

In [31]:
county_votes_df.state.value_counts()

NameError: name 'county_votes_df' is not defined

In [ ]:
len(county_elections_df.county_name.unique())

In [32]:
len(county_elections_df.state.unique())

51

In [33]:
county_elections_df.year.value_counts()

2020    22093
2000    12628
2016     9474
2012     9474
2008     9474
2004     9474
Name: year, dtype: int64

In [34]:
county_elections_df.party.value_counts()

REPUBLICAN     20906
DEMOCRAT       20906
OTHER          19815
GREEN           6035
LIBERTARIAN     4955
Name: party, dtype: int64

In [35]:
county_votes_2020_df=county_elections_df[county_elections_df['year']==2020]
county_votes_2020_df.head()

,year,state,state_po,county_name,county_fips,office,candidate,party,candidatevotes,totalvotes,version,mode
50524,2020,ALABAMA,AL,AUTAUGA,1001.0,US PRESIDENT,JOSEPH R BIDEN JR,DEMOCRAT,7503,27770,20220315,TOTAL
50525,2020,ALABAMA,AL,AUTAUGA,1001.0,US PRESIDENT,OTHER,OTHER,429,27770,20220315,TOTAL
50526,2020,ALABAMA,AL,AUTAUGA,1001.0,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,19838,27770,20220315,TOTAL
50527,2020,ALABAMA,AL,BALDWIN,1003.0,US PRESIDENT,JOSEPH R BIDEN JR,DEMOCRAT,24578,109679,20220315,TOTAL
50528,2020,ALABAMA,AL,BALDWIN,1003.0,US PRESIDENT,OTHER,OTHER,1557,109679,20220315,TOTAL

In [36]:
len(county_votes_2020_df.state.unique())

51

In [37]:
len(county_votes_2020_df.county_name.unique())

1865

In [38]:
county_votes_2020_df.party.value_counts()

REPUBLICAN     5117
DEMOCRAT       5117
LIBERTARIAN    4955
OTHER          4026
GREEN          2878
Name: party, dtype: int64

In [39]:
county_votes_2020_df.party.value_counts()

REPUBLICAN     5117
DEMOCRAT       5117
LIBERTARIAN    4955
OTHER          4026
GREEN          2878
Name: party, dtype: int64

### Elections results by county

In [40]:
county_votes_2020_df['party'].unique()

array(['DEMOCRAT', 'OTHER', 'REPUBLICAN', 'GREEN', 'LIBERTARIAN'],
      dtype=object)

In [41]:
county_votes_2020_df[county_votes_2020_df['county_fips']==4001]

,year,state,state_po,county_name,county_fips,office,candidate,party,candidatevotes,totalvotes,version,mode
50930,2020,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,JOSEPH R BIDEN JR,DEMOCRAT,16460,35172,20220315,EARLY VOTE
50931,2020,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,JOSEPH R BIDEN JR,DEMOCRAT,6539,35172,20220315,ELECTION DAY
50932,2020,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,JOSEPH R BIDEN JR,DEMOCRAT,294,35172,20220315,PROVISIONAL
50933,2020,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,OTHER,GREEN,0,35172,20220315,EARLY VOTE
50934,2020,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,OTHER,GREEN,0,35172,20220315,ELECTION DAY
50935,2020,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,OTHER,GREEN,0,35172,20220315,PROVISIONAL
50936,2020,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,JO JORGENSEN,LIBERTARIAN,311,35172,20220315,EARLY VOTE
50937,2020,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,JO JORGENSEN,LIBERTARIAN,122,35172,20220315,ELECTION DAY
50938,2020,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,JO JORGENSEN,LIBERTARIAN,4,35172,20220315,PROVISIONAL
50939,2020,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,OTHER,OTHER,0,35172,20220315,EARLY VOTE
50940,2020,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,OTHER,OTHER,0,35172,20220315,ELECTION DAY
50941,2020,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,OTHER,OTHER,0,35172,20220315,PROVISIONAL
50942,2020,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,7262,35172,20220315,EARLY VOTE
50943,2020,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,4053,35172,20220315,ELECTION DAY
50944,2020,ARIZONA,AZ,APACHE,4001.0,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,127,35172,20220315,PROVISIONAL

In [42]:
elections_df1 =county_votes_2020_df.drop(columns=['year','state','state_po','office','version','mode'])
elections_df1

,county_name,county_fips,candidate,party,candidatevotes,totalvotes
50524,AUTAUGA,1001.0,JOSEPH R BIDEN JR,DEMOCRAT,7503,27770
50525,AUTAUGA,1001.0,OTHER,OTHER,429,27770
50526,AUTAUGA,1001.0,DONALD J TRUMP,REPUBLICAN,19838,27770
50527,BALDWIN,1003.0,JOSEPH R BIDEN JR,DEMOCRAT,24578,109679
50528,BALDWIN,1003.0,OTHER,OTHER,1557,109679
50529,BALDWIN,1003.0,DONALD J TRUMP,REPUBLICAN,83544,109679
50530,BARBOUR,1005.0,JOSEPH R BIDEN JR,DEMOCRAT,4816,10518
50531,BARBOUR,1005.0,OTHER,OTHER,80,10518
50532,BARBOUR,1005.0,DONALD J TRUMP,REPUBLICAN,5622,10518
50533,BIBB,1007.0,JOSEPH R BIDEN JR,DEMOCRAT,1986,9595
50534,BIBB,1007.0,OTHER,OTHER,84,9595
50535,BIBB,1007.0,DONALD J TRUMP,REPUBLICAN,7525,9595
50536,BLOUNT,1009.0,JOSEPH R BIDEN JR,DEMOCRAT,2640,27588
50537,BLOUNT,1009.0,OTHER,OTHER,237,27588
50538,BLOUNT,1009.0,DONALD J TRUMP,REPUBLICAN,24711,27588
50539,BULLOCK,1011.0,JOSEPH R BIDEN JR,DEMOCRAT,3446,4613
50540,BULLOCK,1011.0,OTHER,OTHER,21,4613
50541,BULLOCK,1011.0,DONALD J TRUMP,REPUBLICAN,1146,4613
50542,BUTLER,1013.0,JOSEPH R BIDEN JR,DEMOCRAT,3965,9488
50543,BUTLER,1013.0,OTHER,OTHER,65,9488
50544,BUTLER,1013.0,DONALD J TRUMP,REPUBLICAN,5458,9488
50545,CALHOUN,1015.0,JOSEPH R BIDEN JR,DEMOCRAT,15216,50983
50546,CALHOUN,1015.0,OTHER,OTHER,666,50983
50547,CALHOUN,1015.0,DONALD J TRUMP,REPUBLICAN,35101,50983
50548,CHAMBERS,1017.0,JOSEPH R BIDEN JR,DEMOCRAT,6365,15284
50549,CHAMBERS,1017.0,OTHER,OTHER,166,15284
50550,CHAMBERS,1017.0,DONALD J TRUMP,REPUBLICAN,8753,15284
50551,CHEROKEE,1019.0,JOSEPH R BIDEN JR,DEMOCRAT,1624,12301
50552,CHEROKEE,1019.0,OTHER,OTHER,94,12301
50553,CHEROKEE,1019.0,DONALD J TRUMP,REPUBLICAN,10583,12301
...,...,...,...,...,...,...
72587,PLATTE,56031.0,OTHER,OTHER,110,4963
72588,PLATTE,56031.0,DONALD J TRUMP,REPUBLICAN,3898,4963
72589,SHERIDAN,56033.0,JOSEPH R BIDEN JR,DEMOCRAT,4043,16546
72590,SHERIDAN,56033.0,JO JORGENSEN,LIBERTARIAN,339,16546
72591,SHERIDAN,56033.0,OTHER,OTHER,321,16546
72592,SHERIDAN,56033.0,DONALD J TRUMP,REPUBLICAN,11843,16546
72593,SUBLETTE,56035.0,JOSEPH R BIDEN JR,DEMOCRAT,882,5000
72594,SUBLETTE,56035.0,JO JORGENSEN,LIBERTARIAN,71,5000
72595,SUBLETTE,56035.0,OTHER,OTHER,90,5000
72596,SUBLETTE,56035.0,DONALD J TRUMP,REPUBLICAN,3957,5000
72597,SWEETWATER,56037.0,JOSEPH R BIDEN JR,DEMOCRAT,3823,16698
72598,SWEETWATER,56037.0,JO JORGENSEN,LIBERTARIAN,350,16698
72599,SWEETWATER,56037.0,OTHER,OTHER,296,16698
72600,SWEETWATER,56037.0,DONALD J TRUMP,REPUBLICAN,12229,16698
72601,TETON,56039.0,JOSEPH R BIDEN JR,DEMOCRAT,9848,14787
72602,TETON,56039.0,JO JORGENSEN,LIBERTARIAN,255,14787
72603,TETON,56039.0,OTHER,OTHER,343,14787
72604,TETON,56039.0,DONALD J TRUMP,REPUBLICAN,4341,14787
72605,UINTA,56041.0,JOSEPH R BIDEN JR,DEMOCRAT,1591,9459
72606,UINTA,56041.0,JO JORGENSEN,LIBERTARIAN,172,9459
72607,UINTA,56041.0,OTHER,OTHER,200,9459
72608,UINTA,56041.0,DONALD J TRUMP,REPUBLICAN,7496,9459
72609,WASHAKIE,56043.0,JOSEPH R BIDEN JR,DEMOCRAT,651,4032
72610,WASHAKIE,56043.0,JO JORGENSEN,LIBERTARIAN,65,4032
72611,WASHAKIE,56043.0,OTHER,OTHER,71,4032
72612,WASHAKIE,56043.0,DONALD J TRUMP,REPUBLICAN,3245,4032
72613,WESTON,56045.0,JOSEPH R BIDEN JR,DEMOCRAT,360,3560
72614,WESTON,56045.0,JO JORGENSEN,LIBERTARIAN,46,3560
72615,WESTON,56045.0,OTHER,OTHER,47,3560
72616,WESTON,56045.0,DONALD J TRUMP,REPUBLICAN,3107,3560

In [43]:
df=elections_df1.pivot_table(index='county_fips', columns = 'party', values = 'candidatevotes', aggfunc='sum')

In [47]:
df

party        DEMOCRAT  GREEN  LIBERTARIAN   OTHER  REPUBLICAN
county_fips
1001.0         7503.0    NaN          NaN   429.0     19838.0
1003.0        24578.0    NaN          NaN  1557.0     83544.0
1005.0         4816.0    NaN          NaN    80.0      5622.0
1007.0         1986.0    NaN          NaN    84.0      7525.0
1009.0         2640.0    NaN          NaN   237.0     24711.0
1011.0         3446.0    NaN          NaN    21.0      1146.0
1013.0         3965.0    NaN          NaN    65.0      5458.0
1015.0        15216.0    NaN          NaN   666.0     35101.0
1017.0         6365.0    NaN          NaN   166.0      8753.0
1019.0         1624.0    NaN          NaN    94.0     10583.0
1021.0         3073.0    NaN          NaN   152.0     16085.0
1023.0         3127.0    NaN          NaN    41.0      4296.0
1025.0         5755.0    NaN          NaN    56.0      7324.0
1027.0         1267.0    NaN          NaN    62.0      5601.0
1029.0          675.0    NaN          NaN    68.0      6484.0
1031.0         5076.0    NaN          NaN   300.0     16899.0
1033.0         8343.0    NaN          NaN   340.0     19203.0
1035.0         2966.0    NaN          NaN    33.0      3442.0
1037.0         1796.0    NaN          NaN    52.0      3631.0
1039.0         2721.0    NaN          NaN   123.0     14586.0
1041.0         1700.0    NaN          NaN    53.0      4864.0
1043.0         4478.0    NaN          NaN   493.0     36880.0
1045.0         5170.0    NaN          NaN   265.0     14303.0
1047.0        12230.0    NaN          NaN   110.0      5524.0
1049.0         4281.0    NaN          NaN   308.0     24767.0
1051.0        10367.0    NaN          NaN   499.0     30164.0
1053.0         4918.0    NaN          NaN   123.0     10869.0
1055.0        11567.0    NaN          NaN   633.0     35528.0
1057.0         1395.0    NaN          NaN    71.0      7300.0
1059.0         2086.0    NaN          NaN   116.0     10376.0
...               ...    ...          ...     ...         ...
55129.0        3867.0    4.0        123.0    50.0      6334.0
55131.0       26650.0   28.0        941.0   214.0     60237.0
55133.0      103906.0   54.0       3023.0  1364.0    159649.0
55135.0        9703.0    4.0        357.0   114.0     18952.0
55137.0        4388.0    0.0        115.0    49.0      9016.0
55139.0       44060.0   38.0       1629.0   509.0     47796.0
55141.0       16365.0    9.0        403.0   213.0     24308.0
56001.0        9092.0    NaN        595.0   478.0      8579.0
56003.0         788.0    NaN         74.0   116.0      4806.0
56005.0        1935.0    NaN        434.0   391.0     16975.0
56007.0        1427.0    NaN        142.0   123.0      5014.0
56009.0         861.0    NaN        121.0   111.0      5917.0
56011.0         378.0    NaN         57.0    57.0      3651.0
56013.0        5519.0    NaN        321.0   387.0     12007.0
56015.0        1203.0    NaN         86.0   105.0      4878.0
56017.0         482.0    NaN         61.0    46.0      1999.0
56019.0         897.0    NaN         86.0    88.0      3881.0
56021.0       15217.0    NaN       1063.0  1066.0     27891.0
56023.0        1509.0    NaN        167.0   206.0      8643.0
56025.0        8530.0    NaN        895.0   695.0     25271.0
56027.0         155.0    NaN         21.0    28.0      1118.0
56029.0        3410.0    NaN        282.0   310.0     12813.0
56031.0         890.0    NaN         65.0   110.0      3898.0
56033.0        4043.0    NaN        339.0   321.0     11843.0
56035.0         882.0    NaN         71.0    90.0      3957.0
56037.0        3823.0    NaN        350.0   296.0     12229.0
56039.0        9848.0    NaN        255.0   343.0      4341.0
56041.0        1591.0    NaN        172.0   200.0      7496.0
56043.0         651.0    NaN         65.0    71.0      3245.0
56045.0         360.0    NaN         46.0    47.0      3107.0

[3153 rows x 5 columns]

In [48]:
df.dtypes

party
DEMOCRAT       float64
GREEN          float64
LIBERTARIAN    float64
OTHER          float64
REPUBLICAN     float64
dtype: object

In [49]:
df2=elections_df1.pivot_table(index='county_name', columns = 'party', values = 'candidatevotes', aggfunc='sum')
df2

party            DEMOCRAT   GREEN  LIBERTARIAN   OTHER  REPUBLICAN
county_name
ABBEVILLE          4101.0    23.0         88.0     6.0      8215.0
ACADIA             5443.0     NaN        241.0   145.0     22596.0
ACCOMACK           7578.0     NaN        188.0    24.0      9172.0
ADA              120539.0     NaN       5310.0  2841.0    130699.0
ADAIR              7687.0    47.0        314.0   140.0     22196.0
ADAMS            186146.0   876.0       6013.0  2719.0    209463.0
ADDISON           15089.0    69.0        248.0   638.0      6567.0
AIKEN             32275.0   274.0        982.0    65.0     51589.0
AITKIN             3607.0    24.0         55.0    81.0      6258.0
ALACHUA           89704.0   302.0       1390.0   236.0     50972.0
ALAMANCE          38825.0   223.0        686.0   301.0     46056.0
ALAMEDA          617659.0  4664.0       6295.0  5143.0    136309.0
ALAMOSA            3759.0    23.0         90.0   123.0      3813.0
ALBANY           108566.0   779.0       2118.0  2348.0     59660.0
ALBEMARLE         42466.0     NaN       1014.0   373.0     20804.0
ALCONA             2142.0    11.0         50.0    13.0      4848.0
ALCORN             2782.0     9.0        118.0    66.0     12818.0
ALEXANDER          5259.0    23.0        134.0    64.0     17374.0
ALEXANDRIA CITY   66240.0     NaN       1022.0   715.0     14544.0
ALFALFA             232.0     NaN         31.0    21.0      1978.0
ALGER              2053.0     9.0         41.0    11.0      3014.0
ALLAMAKEE          2576.0     4.0         71.0    27.0      4744.0
ALLEGAN           24449.0   143.0        943.0   167.0     41392.0
ALLEGANY          15206.0   208.0        646.0   455.0     35021.0
ALLEGHANY          3729.0    15.0        124.0    25.0     10386.0
ALLEGHENY        429065.0     NaN       8344.0     NaN    282324.0
ALLEN             92658.0    29.0       4594.0   295.0    144577.0
ALLENDALE          2718.0    19.0         19.0     2.0       835.0
ALPENA             6000.0    28.0        220.0    35.0     10686.0
ALPINE              476.0     4.0         15.0     2.0       244.0
...                   ...     ...          ...     ...         ...
WOODSON             294.0     NaN         24.0     NaN      1228.0
WOODWARD           1005.0     NaN        125.0    44.0      6611.0
WORCESTER        261333.0  2616.0       7466.0  4943.0    190254.0
WORTH              4206.0     7.0        112.0    36.0     10449.0
WRIGHT            31594.0   294.0       1156.0   801.0     63574.0
WYANDOT            2733.0     NaN        155.0    40.0      8462.0
WYANDOTTE         36788.0     NaN       1063.0     NaN     18934.0
WYOMING           10934.0    79.0        551.0   182.0     31187.0
WYTHE              3143.0     NaN        170.0    27.0     11733.0
YADKIN             3763.0    28.0        131.0    68.0     15933.0
YAKIMA            43179.0   321.0       1425.0   713.0     50555.0
YALOBUSHA          2785.0     7.0         26.0    46.0      3671.0
YAMHILL           27174.0   254.0       1448.0   496.0     29551.0
YANCEY             3688.0    27.0         82.0    39.0      7516.0
YANKTON            4016.0     NaN        303.0     NaN      6581.0
YATES              4219.0    40.0        165.0   156.0      6208.0
YAVAPAI           49602.0     0.0       2092.0     0.0     91527.0
YAZOO              5496.0     8.0         21.0    79.0      4832.0
YELL               1284.0    14.0         66.0   151.0      5226.0
YELLOW MEDICINE    1688.0    11.0         45.0    50.0      3734.0
YELLOWSTONE       30679.0     NaN       2370.0     NaN     50772.0
YOAKUM              420.0     6.0         31.0     0.0      2174.0
YOLO              67598.0   547.0       1206.0   651.0     27292.0
YORK             237624.0  1657.0       8476.0  1885.0    309855.0
YOUNG              1034.0    18.0         76.0     1.0      7110.0
YUBA              11230.0   124.0        510.0   256.0     17676.0
YUMA              32995.0     2.0       1189.0    35.0     40641.0
ZAPATA             1826.0     4.0         11.0     0.0      2033.0
ZAVALA             2864.0    12.0         13.0     0.0      1490.0
ZIEBACH             481.0     NaN         21.0     NaN       404.0

[1865 rows x 5 columns]

In [255]:
df2.fillna(0, inplace=True)
df2

party        DEMOCRAT  GREEN  LIBERTARIAN   OTHER  REPUBLICAN
county_name
ABBEVILLE      4101.0   23.0         88.0     6.0      8215.0
ACADIA         5443.0    0.0        241.0   145.0     22596.0
ACCOMACK       7578.0    0.0        188.0    24.0      9172.0
ADA          120539.0    0.0       5310.0  2841.0    130699.0
ADAIR          7687.0   47.0        314.0   140.0     22196.0
...               ...    ...          ...     ...         ...
YUBA          11230.0  124.0        510.0   256.0     17676.0
YUMA          32995.0    2.0       1189.0    35.0     40641.0
ZAPATA         1826.0    4.0         11.0     0.0      2033.0
ZAVALA         2864.0   12.0         13.0     0.0      1490.0
ZIEBACH         481.0    0.0         21.0     0.0       404.0

[1865 rows x 5 columns]

In [50]:
df2.dtypes

party
DEMOCRAT       float64
GREEN          float64
LIBERTARIAN    float64
OTHER          float64
REPUBLICAN     float64
dtype: object

In [51]:
#Creating the winner column in order to know which party won
df2['WINNER'] = np.where((df2['DEMOCRAT'] > df2['REPUBLICAN']),1 , 0)

In [52]:
df2

party            DEMOCRAT   GREEN  LIBERTARIAN   OTHER  REPUBLICAN  WINNER
county_name
ABBEVILLE          4101.0    23.0         88.0     6.0      8215.0       0
ACADIA             5443.0     NaN        241.0   145.0     22596.0       0
ACCOMACK           7578.0     NaN        188.0    24.0      9172.0       0
ADA              120539.0     NaN       5310.0  2841.0    130699.0       0
ADAIR              7687.0    47.0        314.0   140.0     22196.0       0
ADAMS            186146.0   876.0       6013.0  2719.0    209463.0       0
ADDISON           15089.0    69.0        248.0   638.0      6567.0       1
AIKEN             32275.0   274.0        982.0    65.0     51589.0       0
AITKIN             3607.0    24.0         55.0    81.0      6258.0       0
ALACHUA           89704.0   302.0       1390.0   236.0     50972.0       1
ALAMANCE          38825.0   223.0        686.0   301.0     46056.0       0
ALAMEDA          617659.0  4664.0       6295.0  5143.0    136309.0       1
ALAMOSA            3759.0    23.0         90.0   123.0      3813.0       0
ALBANY           108566.0   779.0       2118.0  2348.0     59660.0       1
ALBEMARLE         42466.0     NaN       1014.0   373.0     20804.0       1
ALCONA             2142.0    11.0         50.0    13.0      4848.0       0
ALCORN             2782.0     9.0        118.0    66.0     12818.0       0
ALEXANDER          5259.0    23.0        134.0    64.0     17374.0       0
ALEXANDRIA CITY   66240.0     NaN       1022.0   715.0     14544.0       1
ALFALFA             232.0     NaN         31.0    21.0      1978.0       0
ALGER              2053.0     9.0         41.0    11.0      3014.0       0
ALLAMAKEE          2576.0     4.0         71.0    27.0      4744.0       0
ALLEGAN           24449.0   143.0        943.0   167.0     41392.0       0
ALLEGANY          15206.0   208.0        646.0   455.0     35021.0       0
ALLEGHANY          3729.0    15.0        124.0    25.0     10386.0       0
ALLEGHENY        429065.0     NaN       8344.0     NaN    282324.0       1
ALLEN             92658.0    29.0       4594.0   295.0    144577.0       0
ALLENDALE          2718.0    19.0         19.0     2.0       835.0       1
ALPENA             6000.0    28.0        220.0    35.0     10686.0       0
ALPINE              476.0     4.0         15.0     2.0       244.0       1
...                   ...     ...          ...     ...         ...     ...
WOODSON             294.0     NaN         24.0     NaN      1228.0       0
WOODWARD           1005.0     NaN        125.0    44.0      6611.0       0
WORCESTER        261333.0  2616.0       7466.0  4943.0    190254.0       1
WORTH              4206.0     7.0        112.0    36.0     10449.0       0
WRIGHT            31594.0   294.0       1156.0   801.0     63574.0       0
WYANDOT            2733.0     NaN        155.0    40.0      8462.0       0
WYANDOTTE         36788.0     NaN       1063.0     NaN     18934.0       1
WYOMING           10934.0    79.0        551.0   182.0     31187.0       0
WYTHE              3143.0     NaN        170.0    27.0     11733.0       0
YADKIN             3763.0    28.0        131.0    68.0     15933.0       0
YAKIMA            43179.0   321.0       1425.0   713.0     50555.0       0
YALOBUSHA          2785.0     7.0         26.0    46.0      3671.0       0
YAMHILL           27174.0   254.0       1448.0   496.0     29551.0       0
YANCEY             3688.0    27.0         82.0    39.0      7516.0       0
YANKTON            4016.0     NaN        303.0     NaN      6581.0       0
YATES              4219.0    40.0        165.0   156.0      6208.0       0
YAVAPAI           49602.0     0.0       2092.0     0.0     91527.0       0
YAZOO              5496.0     8.0         21.0    79.0      4832.0       1
YELL               1284.0    14.0         66.0   151.0      5226.0       0
YELLOW MEDICINE    1688.0    11.0         45.0    50.0      3734.0       0
YELLOWSTONE       30679.0     NaN       2370.0     NaN     50772.0       0
YOAKUM              420.0     6.0         31.0     0.0      2174.0       0
YOLO              67598.0   547.0       1206.0   651.0     27292.0       1
YORK             237624.0  1657.0       8476.0  1885.0    309855.0       0
YOUNG              1034.0    18.0         76.0     1.0      7110.0       0
YUBA              11230.0   124.0        510.0   256.0     17676.0       0
YUMA              32995.0     2.0       1189.0    35.0     40641.0       0
ZAPATA             1826.0     4.0         11.0     0.0      2033.0       0
ZAVALA             2864.0    12.0         13.0     0.0      1490.0       1
ZIEBACH             481.0     NaN         21.0     NaN       404.0       1

[1865 rows x 6 columns]

In [259]:
df2.to_csv("elections2020_clean.csv")

In [260]:
df2.dtypes

party
DEMOCRAT       float64
GREEN          float64
LIBERTARIAN    float64
OTHER          float64
REPUBLICAN     float64
WINNER           int32
dtype: object

In [66]:
df2.to_sql('elections2020_clean', con = engine, if_exists = 'replace')

# POPOULATION_COUNTY DATABASE

In [54]:
pop_df=pd.read_csv(pop_to_load,engine='python',encoding='latin1')
pop_df.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2019,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015,RNETMIG2016,RNETMIG2017,RNETMIG2018,RNETMIG2019
0,40,3,6,1,0,Alabama,Alabama,4779736,4780125,4785437,...,1.917501,0.578434,1.186314,1.522549,0.563489,0.626357,0.745172,1.090366,1.773786,2.483744
1,50,3,6,1,1,Alabama,Autauga County,54571,54597,54773,...,4.847310,6.018182,-6.226119,-3.902226,1.970443,-1.712875,4.777171,0.849656,0.540916,4.560062
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183112,...,24.017829,16.641870,17.488579,22.751474,20.184334,17.725964,21.279291,22.398256,24.727215,24.380567
3,50,3,6,1,5,Alabama,Barbour County,27457,27455,27327,...,-5.690302,0.292676,-6.897817,-8.132185,-5.140431,-15.724575,-18.238016,-24.998528,-8.754922,-5.165664
4,50,3,6,1,7,Alabama,Bibb County,22915,22915,22870,...,1.385134,-4.998356,-3.787545,-5.797999,1.331144,1.329817,-0.708717,-3.234669,-6.857092,1.831952

In [55]:
pop_df.count()

SUMLEV                   3193
REGION                   3193
DIVISION                 3193
STATE                    3193
COUNTY                   3193
STNAME                   3193
CTYNAME                  3193
CENSUS2010POP            3193
ESTIMATESBASE2010        3193
POPESTIMATE2010          3193
POPESTIMATE2011          3193
POPESTIMATE2012          3193
POPESTIMATE2013          3193
POPESTIMATE2014          3193
POPESTIMATE2015          3193
POPESTIMATE2016          3193
POPESTIMATE2017          3193
POPESTIMATE2018          3193
POPESTIMATE2019          3193
NPOPCHG_2010             3193
NPOPCHG_2011             3193
NPOPCHG_2012             3193
NPOPCHG_2013             3193
NPOPCHG_2014             3193
NPOPCHG_2015             3193
NPOPCHG_2016             3193
NPOPCHG_2017             3193
NPOPCHG_2018             3193
NPOPCHG_2019             3193
BIRTHS2010               3193
                         ...
RNATURALINC2017          3193
RNATURALINC2018          3193
RNATURALINC2019          3193
RINTERNATIONALMIG2011    3193
RINTERNATIONALMIG2012    3193
RINTERNATIONALMIG2013    3193
RINTERNATIONALMIG2014    3193
RINTERNATIONALMIG2015    3193
RINTERNATIONALMIG2016    3193
RINTERNATIONALMIG2017    3193
RINTERNATIONALMIG2018    3193
RINTERNATIONALMIG2019    3193
RDOMESTICMIG2011         3193
RDOMESTICMIG2012         3193
RDOMESTICMIG2013         3193
RDOMESTICMIG2014         3193
RDOMESTICMIG2015         3193
RDOMESTICMIG2016         3193
RDOMESTICMIG2017         3193
RDOMESTICMIG2018         3193
RDOMESTICMIG2019         3193
RNETMIG2011              3193
RNETMIG2012              3193
RNETMIG2013              3193
RNETMIG2014              3193
RNETMIG2015              3193
RNETMIG2016              3193
RNETMIG2017              3193
RNETMIG2018              3193
RNETMIG2019              3193
Length: 164, dtype: int64

In [56]:
print(pop_df.columns)

Index(['SUMLEV', 'REGION', 'DIVISION', 'STATE', 'COUNTY', 'STNAME', 'CTYNAME',
       'CENSUS2010POP', 'ESTIMATESBASE2010', 'POPESTIMATE2010',
       ...
       'RDOMESTICMIG2019', 'RNETMIG2011', 'RNETMIG2012', 'RNETMIG2013',
       'RNETMIG2014', 'RNETMIG2015', 'RNETMIG2016', 'RNETMIG2017',
       'RNETMIG2018', 'RNETMIG2019'],
      dtype='object', length=164)

In [57]:
new_column_order= ["STNAME",
                   "CTYNAME",
                  "POPESTIMATE2019",
                  "INTERNATIONALMIG2019"]
pop_df=pop_df[new_column_order]
pop_df

         STNAME             CTYNAME  POPESTIMATE2019  INTERNATIONALMIG2019
0       Alabama             Alabama          4903185                  2772
1       Alabama      Autauga County            55869                   -16
2       Alabama      Baldwin County           223234                    80
3       Alabama      Barbour County            24686                    13
4       Alabama         Bibb County            22394                    10
5       Alabama       Blount County            57826                     6
6       Alabama      Bullock County            10101                    -1
7       Alabama       Butler County            19448                    18
8       Alabama      Calhoun County           113605                    14
9       Alabama     Chambers County            33254                     6
10      Alabama     Cherokee County            26196                    -3
11      Alabama      Chilton County            44428                    35
12      Alabama      Choctaw County            12589                    -2
13      Alabama       Clarke County            23622                    -5
14      Alabama         Clay County            13235                    -2
15      Alabama     Cleburne County            14910                   -11
16      Alabama       Coffee County            52342                    34
17      Alabama      Colbert County            55241                    73
18      Alabama      Conecuh County            12067                     1
19      Alabama        Coosa County            10663                    13
20      Alabama    Covington County            37049                    -5
21      Alabama     Crenshaw County            13772                     3
22      Alabama      Cullman County            83768                    34
23      Alabama         Dale County            49172                    18
24      Alabama       Dallas County            37196                     5
25      Alabama       DeKalb County            71513                    44
26      Alabama       Elmore County            81209                    25
27      Alabama     Escambia County            36633                    -1
28      Alabama       Etowah County           102268                    37
29      Alabama      Fayette County            16302                     5
...         ...                 ...              ...                   ...
3163  Wisconsin   Washington County           136034                    22
3164  Wisconsin     Waukesha County           404198                   151
3165  Wisconsin      Waupaca County            50990                    17
3166  Wisconsin     Waushara County            24443                    14
3167  Wisconsin    Winnebago County           171907                    65
3168  Wisconsin         Wood County            72999                    17
3169    Wyoming             Wyoming           578759                   538
3170    Wyoming       Albany County            38880                   259
3171    Wyoming     Big Horn County            11790                     2
3172    Wyoming     Campbell County            46341                    33
3173    Wyoming       Carbon County            14800                     8
3174    Wyoming     Converse County            13822                     5
3175    Wyoming        Crook County             7584                    20
3176    Wyoming      Fremont County            39261                    -3
3177    Wyoming       Goshen County            13211                     6
3178    Wyoming  Hot Springs County             4413                     1
3179    Wyoming      Johnson County             8445                     2
3180    Wyoming      Laramie County            99500                     1
3181    Wyoming      Lincoln County            19830                     0
3182    Wyoming      Natrona County            79858                   103
3183    Wyoming     Niobrara County             2356                     0
3184    Wyoming         Park County            29194                   -10
3185    Wyoming       Platte County             8393                   -10
3186    Wyoming     Sheridan County            30485                    14
3187    Wyoming     Sublette County             9831                    -8
3188    Wyoming   Sweetwater County            42343                    23
3189    Wyoming        Teton County            23464                    79
3190    Wyoming        Uinta County            20226                     0
3191    Wyoming     Washakie County             7805                    -5
3192    Wyoming       Weston County             6927                    18

[3193 rows x 4 columns]

In [58]:
pop_df.count()

STNAME                  3193
CTYNAME                 3193
POPESTIMATE2019         3193
INTERNATIONALMIG2019    3193
dtype: int64

In [59]:
pop_df['county_name'] = pop_df['CTYNAME'].str.split(' ').str[0]
pop_df['county_name'] = pop_df['county_name'].str.upper()

In [60]:
new_column_order= ["STNAME",
                   'county_name',
                  "POPESTIMATE2019",
                  "INTERNATIONALMIG2019"]
pop_df=pop_df[new_column_order]
pop_df

         STNAME county_name  POPESTIMATE2019  INTERNATIONALMIG2019
0       Alabama     ALABAMA          4903185                  2772
1       Alabama     AUTAUGA            55869                   -16
2       Alabama     BALDWIN           223234                    80
3       Alabama     BARBOUR            24686                    13
4       Alabama        BIBB            22394                    10
5       Alabama      BLOUNT            57826                     6
6       Alabama     BULLOCK            10101                    -1
7       Alabama      BUTLER            19448                    18
8       Alabama     CALHOUN           113605                    14
9       Alabama    CHAMBERS            33254                     6
10      Alabama    CHEROKEE            26196                    -3
11      Alabama     CHILTON            44428                    35
12      Alabama     CHOCTAW            12589                    -2
13      Alabama      CLARKE            23622                    -5
14      Alabama        CLAY            13235                    -2
15      Alabama    CLEBURNE            14910                   -11
16      Alabama      COFFEE            52342                    34
17      Alabama     COLBERT            55241                    73
18      Alabama     CONECUH            12067                     1
19      Alabama       COOSA            10663                    13
20      Alabama   COVINGTON            37049                    -5
21      Alabama    CRENSHAW            13772                     3
22      Alabama     CULLMAN            83768                    34
23      Alabama        DALE            49172                    18
24      Alabama      DALLAS            37196                     5
25      Alabama      DEKALB            71513                    44
26      Alabama      ELMORE            81209                    25
27      Alabama    ESCAMBIA            36633                    -1
28      Alabama      ETOWAH           102268                    37
29      Alabama     FAYETTE            16302                     5
...         ...         ...              ...                   ...
3163  Wisconsin  WASHINGTON           136034                    22
3164  Wisconsin    WAUKESHA           404198                   151
3165  Wisconsin     WAUPACA            50990                    17
3166  Wisconsin    WAUSHARA            24443                    14
3167  Wisconsin   WINNEBAGO           171907                    65
3168  Wisconsin        WOOD            72999                    17
3169    Wyoming     WYOMING           578759                   538
3170    Wyoming      ALBANY            38880                   259
3171    Wyoming         BIG            11790                     2
3172    Wyoming    CAMPBELL            46341                    33
3173    Wyoming      CARBON            14800                     8
3174    Wyoming    CONVERSE            13822                     5
3175    Wyoming       CROOK             7584                    20
3176    Wyoming     FREMONT            39261                    -3
3177    Wyoming      GOSHEN            13211                     6
3178    Wyoming         HOT             4413                     1
3179    Wyoming     JOHNSON             8445                     2
3180    Wyoming     LARAMIE            99500                     1
3181    Wyoming     LINCOLN            19830                     0
3182    Wyoming     NATRONA            79858                   103
3183    Wyoming    NIOBRARA             2356                     0
3184    Wyoming        PARK            29194                   -10
3185    Wyoming      PLATTE             8393                   -10
3186    Wyoming    SHERIDAN            30485                    14
3187    Wyoming    SUBLETTE             9831                    -8
3188    Wyoming  SWEETWATER            42343                    23
3189    Wyoming       TETON            23464                    79
3190    Wyoming       UINTA            20226                     0
3191    Wyoming    WASHAKIE             7805                    -5
3192    Wyoming      WESTON             6927                    18

[3193 rows x 4 columns]

In [61]:
pop_clean_df= pop_df.drop_duplicates (subset= 'county_name', keep='last')

In [62]:
pop_clean_df[pop_clean_df['county_name']=='ALEUTIANS']

    STNAME county_name  POPESTIMATE2019  INTERNATIONALMIG2019
70  Alaska   ALEUTIANS             5634                    53

In [63]:
pop_clean_df

         STNAME    county_name  POPESTIMATE2019  INTERNATIONALMIG2019
0       Alabama        ALABAMA          4903185                  2772
1       Alabama        AUTAUGA            55869                   -16
6       Alabama        BULLOCK            10101                    -1
11      Alabama        CHILTON            44428                    35
17      Alabama        COLBERT            55241                    73
18      Alabama        CONECUH            12067                     1
19      Alabama          COOSA            10663                    13
21      Alabama       CRENSHAW            13772                     3
22      Alabama        CULLMAN            83768                    34
23      Alabama           DALE            49172                    18
28      Alabama         ETOWAH           102268                    37
31      Alabama         GENEVA            26271                    -7
46      Alabama        MARENGO            18863                     3
49      Alabama         MOBILE           413210                   266
61      Alabama      TALLADEGA            79978                    32
62      Alabama     TALLAPOOSA            40367                     2
63      Alabama     TUSCALOOSA           209355                   221
68       Alaska         ALASKA           731545                   659
70       Alaska      ALEUTIANS             5634                    53
71       Alaska      ANCHORAGE           288000                   364
72       Alaska         BETHEL            18386                     2
74       Alaska         DENALI             2097                     8
75       Alaska     DILLINGHAM             4916                     1
76       Alaska      FAIRBANKS            96849                    16
77       Alaska         HAINES             2530                     0
78       Alaska  HOONAH-ANGOON             2148                     4
80       Alaska          KENAI            58708                    20
81       Alaska      KETCHIKAN            13901                    24
82       Alaska         KODIAK            12998                    33
83       Alaska       KUSILVAK             8314                     7
...         ...            ...              ...                   ...
3163  Wisconsin     WASHINGTON           136034                    22
3164  Wisconsin       WAUKESHA           404198                   151
3165  Wisconsin        WAUPACA            50990                    17
3166  Wisconsin       WAUSHARA            24443                    14
3167  Wisconsin      WINNEBAGO           171907                    65
3168  Wisconsin           WOOD            72999                    17
3169    Wyoming        WYOMING           578759                   538
3170    Wyoming         ALBANY            38880                   259
3171    Wyoming            BIG            11790                     2
3172    Wyoming       CAMPBELL            46341                    33
3173    Wyoming         CARBON            14800                     8
3174    Wyoming       CONVERSE            13822                     5
3175    Wyoming          CROOK             7584                    20
3176    Wyoming        FREMONT            39261                    -3
3177    Wyoming         GOSHEN            13211                     6
3178    Wyoming            HOT             4413                     1
3179    Wyoming        JOHNSON             8445                     2
3180    Wyoming        LARAMIE            99500                     1
3181    Wyoming        LINCOLN            19830                     0
3182    Wyoming        NATRONA            79858                   103
3183    Wyoming       NIOBRARA             2356                     0
3184    Wyoming           PARK            29194                   -10
3185    Wyoming         PLATTE             8393                   -10
3186    Wyoming       SHERIDAN            30485                    14
3187    Wyoming       SUBLETTE             9831                    -8
3188    Wyoming     SWEETWATER            42343                    23
3189    Wyoming          TETON            23464                    79
3190    Wyoming          UINTA            20226                     0
3191    Wyoming       WASHAKIE             7805                    -5
3192    Wyoming         WESTON             6927                    18

[1768 rows x 4 columns]

In [247]:
pop_clean_df.to_csv("pop_clean.csv", index=False)

In [64]:
#Export to Database
pop_clean_df.to_sql('pop_clean', con = engine, index=False, if_exists = 'replace')

In [70]:
# final database

META_DATA = MetaData(bind=engine, reflect=True)

main_database = META_DATA.tables['main_database']

C:\Users\alelo\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:3: SADeprecationWarning: The MetaData.reflect flag is deprecated and will be removed in a future release.   Please use the MetaData.reflect() method.
  This is separate from the ipykernel package so we can avoid doing imports until

In [71]:
main_database

Table('main_database', MetaData(bind=Engine(postgresql://ElectionTeam:***@final-data-project.cxtxzq2kyq9u.us-east-1.rds.amazonaws.com:5432/election_data)), Column('county_name', TEXT(), table=<main_database>), Column('POPESTIMATE2019', BIGINT(), table=<main_database>), Column('INTERNATIONALMIG2019', BIGINT(), table=<main_database>), Column('DEMOCRAT', DOUBLE_PRECISION(precision=53), table=<main_database>), Column('REPUBLICAN', DOUBLE_PRECISION(precision=53), table=<main_database>), Column('LIBERTARIAN', DOUBLE_PRECISION(precision=53), table=<main_database>), Column('GREEN', DOUBLE_PRECISION(precision=53), table=<main_database>), Column('OTHER', DOUBLE_PRECISION(precision=53), table=<main_database>), Column('WINNER', INTEGER(), table=<main_database>), Column('Debt_All', TEXT(), table=<main_database>), Column('Debt_Communities_Color', TEXT(), table=<main_database>), Column('Debt_Majorities_White', TEXT(), table=<main_database>), Column('Avg_Household_Income_All', BIGINT(), table=<main_database>), Column('Avg_Non_White_Income', TEXT(), table=<main_database>), Column('Avg_Non_Hispanic', BIGINT(), table=<main_database>), schema=None)

In [76]:
main_data_df =pd.read_sql_table("main_database", con= engine)

In [77]:
main_data_df

,county_name,POPESTIMATE2019,INTERNATIONALMIG2019,DEMOCRAT,REPUBLICAN,LIBERTARIAN,GREEN,OTHER,WINNER,Debt_All,Debt_Communities_Color,Debt_Majorities_White,Avg_Household_Income_All,Avg_Non_White_Income,Avg_Non_Hispanic
0,ABBEVILLE,24527,-11,4101.0,8215.0,88.0,23.0,6.0,0,.214653,49,.2151163,53822,37805,61259
1,ACADIA,62045,17,5443.0,22596.0,241.0,NaN,145.0,0,.3015544,49,.3034773,61465,36608,67627
2,ACCOMACK,32316,30,7578.0,9172.0,188.0,NaN,24.0,0,.2738408,.2742616,.2801664,63100,49308,69458
3,ADA,481587,26,120539.0,130699.0,5310.0,NaN,2841.0,0,.3067449,49,.3079475,96684,83899,98374
4,ADAIR,22194,3,7687.0,22196.0,314.0,47.0,140.0,0,.3387574,.3504464,49,46729,45996,47520
5,ADAMS,20220,8,186146.0,209463.0,6013.0,876.0,2719.0,0,.2952503,49,.2956298,59975,51616,60370
6,ADDISON,36777,20,15089.0,6567.0,248.0,69.0,638.0,1,.3795435,49,.3777589,84865,82496,84970
7,AIKEN,170872,140,32275.0,51589.0,982.0,274.0,65.0,0,.3067181,49,.3090074,70238,54275,77535
8,AITKIN,15886,-1,3607.0,6258.0,55.0,24.0,81.0,0,.3187391,49,.3187391,62069,51466,62548
9,ALACHUA,269043,798,89704.0,50972.0,1390.0,302.0,236.0,1,.2544899,.2406015,.274381,73143,61231,79695
10,ALAMANCE,169509,67,38825.0,46056.0,686.0,223.0,301.0,0,.3277085,49,.3341671,71555,54204,79529
11,ALAMEDA,1671329,8540,617659.0,136309.0,6295.0,4664.0,5143.0,1,.2097298,.2187864,.1937244,141427,128196,162954
12,ALAMOSA,16233,-4,3759.0,3813.0,90.0,23.0,123.0,0,.2862986,49,49,56513,49816,63021
13,ALBANY,38880,259,108566.0,59660.0,2118.0,779.0,2348.0,1,.3012704,49,.3018182,68577,50818,71760
14,ALBEMARLE,109330,133,42466.0,20804.0,1014.0,NaN,373.0,1,.2463726,49,.2455143,120456,108244,123010
15,ALCONA,10405,3,2142.0,4848.0,50.0,11.0,13.0,0,.3172043,49,.3172043,52435,33023,52881
16,ALCORN,36953,-7,2782.0,12818.0,118.0,9.0,66.0,0,.2901057,49,.2934249,58260,55498,58731
17,ALEXANDER,37497,0,5259.0,17374.0,134.0,23.0,64.0,0,.3196172,49,.3196172,68416,46919,70258
18,ALFALFA,5702,6,232.0,1978.0,31.0,NaN,21.0,0,.3053435,49,.3053435,81944,72404,82557
19,ALGER,9108,4,2053.0,3014.0,41.0,9.0,11.0,0,.3109541,49,.3109541,55675,54327,55776
20,ALLAMAKEE,13687,16,2576.0,4744.0,71.0,4.0,27.0,0,.3089431,49,.3089431,65543,48403,66647
21,ALLEGAN,118081,49,24449.0,41392.0,943.0,143.0,167.0,0,.2966125,49,.296756,78236,57001,80280
22,ALLEGANY,46091,28,15206.0,35021.0,646.0,208.0,455.0,0,.3687023,49,.3681783,62811,63027,62806
23,ALLEGHANY,14860,-5,3729.0,10386.0,124.0,15.0,25.0,0,.2418773,49,.2418773,62034,41048,63658
24,ALLEGHENY,1216045,2392,429065.0,282324.0,8344.0,NaN,NaN,1,.3434123,.2520548,.3480793,91448,66769,97264
25,ALLEN,102351,-8,92658.0,144577.0,4594.0,29.0,295.0,0,.3415716,49,.3422392,67471,52232,70738
26,ALLENDALE,8688,9,2718.0,835.0,19.0,19.0,2.0,1,.1895161,.1882845,49,43514,36688,65836
27,ALPENA,28405,8,6000.0,10686.0,220.0,28.0,35.0,0,.3463074,49,.3463074,57448,70938,57068
28,ALPINE,1129,1,476.0,244.0,15.0,4.0,2.0,1,49,49,49,97724,73313,106429
29,AMADOR,39752,17,8153.0,13585.0,349.0,110.0,107.0,0,.2668178,49,.2659574,81659,77760,82222
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1589,WOODRUFF,6320,0,856.0,1543.0,14.0,6.0,57.0,0,.2924528,49,.3495146,51320,33486,58338
1590,WOODS,8793,6,591.0,2993.0,66.0,NaN,28.0,0,.3253968,49,.3253968,68430,53300,69875
1591,WOODSON,3138,0,294.0,1228.0,24.0,NaN,NaN,0,.2254902,49,.2254902,51321,27513,52840
1592,WOODWARD,20211,22,1005.0,6611.0,125.0,NaN,44.0,0,.2996689,49,.3064516,77153,56968,79901
1593,WORCESTER,830622,2155,261333.0,190254.0,7466.0,2616.0,4943.0,1,.3528311,.2666667,.3604133,101636,87778,105066
1594,WORTH,2013,0,4206.0,10449.0,112.0,7.0,36.0,0,.2051282,49,.2051282,59673,26918,60098
1595,WRIGHT,18289,-7,31594.0,63574.0,1156.0,294.0,801.0,0,.2879046,49,.2879046,48932,88603,47331
1596,WYANDOT,21772,-5,2733.0,8462.0,155.0,NaN,40.0,0,.3310992,49,.3310992,68514,51937,69040
1597,WYANDOTTE,165429,500,36788.0,18934.0,1063.0,NaN,NaN,1,.250315,.2289463,.3213429,58167,49185,69067
1598,WYOMING,578759,538,10934.0,31187.0,551.0,79.0,182.0,0,.4025356,49,.4028893,55480,68018,55181
1599,WYTHE,28684,-7,3143.0,11733.0,170.0,NaN,27.0,0,.3686975,49,.3686975,64960,43557,65968
1600,YADKIN,37667,18,3763.0,15933.0,131.0,28.0,68.0,0,.28474,49,.28474,59932,50215,61002
1601,YAKIMA,250873,-137,43179.0,50555.0,1425.0,321.0,713.0,0,.298575,.3035088,.3193379,72179,63149,79239
1602,YALOBUSHA,12108,-3,2785.0,3671.0,26.0,7.0,46.0,0,.352657,49,.3449612,49019,39562,55058
1603,YAMHILL,107100,-45,27174.0,29551.0,1448.0,254.0,496.0,0,.3016688,49,.2964092,84219,78234,85452
1604,YANCEY,18069,-2,3688.0,7516.0,82.0,27.0,39.0,0,.2958801,49,.2977099,56153,39655,56918
1605,YATES,24913,10,4219.0,6208.0,165.0,40.0,156.0,0,.3198128,49,.3192488,74877,43977,75819
1606,YAVAPAI,235099,-72,49602.0,91527.0,2092.0,0.0,0.0,0,.2650986,49,.2637445,71282,70313,71439
1607,YAZOO,29690,43,5496.0,4832.0,21.0,8.0,79.0,1,.2532751,.2336634,.3035714,53676,47153,62538
1608,YELL,21341,-2,1284.0,5226.0,66.0,14.0,151.0,0,.336,49,.3344103,59191,48067,61702
1609,YELLOWSTONE,161300,43,30679.0,50772.0,2370.0,NaN,NaN,0,.306294,49,.3080899,88264,57513,91897
1610,YOAKUM,8713,48,420.0,2174.0,31.0,6.0,0.0,0,.3653846,.3653846,49,80243,74873,89170
1611,YOLO,220500,857,67598.0,27292.0,1206.0,547.0,651.0,1,.2320026,.3171247,49,107375,82925,127855
1612,YORK,68280,67,237624.0,309855.0,8476.0,1657.0,1885.0,0,.33268,49,.3236423,113116,133697,106425
1613,YOUNG,18010,9,1034.0,7110.0,76.0,18.0,1.0,0,.3146417,49,.3135726,67391,54849,69414
1614,YUBA,78668,0,11230.0,17676.0,510.0,124.0,256.0,0,.3227057,49,.3132832,74158,89280,67440
1615,YUMA,10019,47,32995.0,40641.0,1189.0,2.0,35.0,0,.3208191,49,.3208191,68157,46145,72859
1616,ZAPATA,14179,-9,1826.0,2033.0,11.0,4.0,0.0,0,.2682927,.2682927,49,60551,60332,63099
1617,ZAVALA,11840,-2,2864.0,1490.0,13.0,12.0,0.0,1,.3147541,.3125,49,41014,40857,46127
1618,ZIEBACH,2756,0,481.0,404.0,21.0,NaN,NaN,1,49,49,49,52721,42990,73559